services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - ENV_COPY=${ENV_COPY:-production}
        - NEXT_PUBLIC_MAINTENANCE_MODE=${NEXT_PUBLIC_MAINTENANCE_MODE}
        - NEXT_PUBLIC_COMING_SOON_MODE=${NEXT_PUBLIC_COMING_SOON_MODE}
    ports:
      - "3000:3000"
    # env_file:
      # - .env.${ENV_COPY}
    environment:
      - NEXT_PUBLIC_MAINTENANCE_MODE=${NEXT_PUBLIC_MAINTENANCE_MODE}
      - NEXT_PUBLIC_COMING_SOON_MODE=${NEXT_PUBLIC_COMING_SOON_MODE}
    networks:
      - server

networks:
  server:
    name: server
