services:
  # SQLite Database is embedded in backend service

  # Backend Service
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - DATABASE_PATH=${DATABASE_PATH:-./data/app.db}
        - AWS_ACCESS_KEY=${AWS_ACCESS_KEY:-aws_access_key}
        - AWS_SECRET_KEY=${AWS_SECRET_KEY:-aws_secret_key}
        - AWS_REGION=${AWS_REGION:-us-east-1}
        - S3_BUCKET=${S3_BUCKET:-bucket_name}
        - S3_ENDPOINT=${S3_ENDPOINT:-s3_endpoint}
        - S3_PROTECTED_BUCKET=${S3_PROTECTED_BUCKET:-s3_protected_bucket}
        - AWS_PROTECTED_ACCESS_KEY=${AWS_PROTECTED_ACCESS_KEY:-aws_protected_access_key}
        - AWS_PROTECTED_SECRET_KEY=${AWS_PROTECTED_SECRET_KEY:-aws_protected_secret_key}
        - S3_PROTECTED_ENDPOINT=${S3_PROTECTED_ENDPOINT:-s3_protected_endpoint}
        - FAUCET_PRIVATE_KEY=${FAUCET_PRIVATE_KEY:-faucet_private_key}
        - RPC_URL=${RPC_URL:-rpc_url}
        - CHAIN_ID=${CHAIN_ID:-chain_id}
        - JWT_SECRET_KEY=${JWT_SECRET_KEY:-jwt_secret_key}
        - POSTMARK_SERVER_TOKEN=${POSTMARK_SERVER_TOKEN:-postmark_token}
        - FROM_EMAIL=${FROM_EMAIL:-noreply@yourapp.com}
        - FROM_EMAIL_NEWS=${FROM_EMAIL_NEWS:-news@yourapp.com}
        - FROM_EMAIL_UPDATES=${FROM_EMAIL_UPDATES:-updates@yourapp.com}
        - POSTHOG_API_KEY=${POSTHOG_API_KEY:-posthog_key}
        - POSTHOG_HOST=${POSTHOG_HOST:-https://app.posthog.com}
        - GOOGLE_TRANSLATE_API_KEY=${GOOGLE_TRANSLATE_API_KEY:-google_translate_api_key}
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    networks:
      - server
    volumes:
      - backend_data:/root/data
    command:
      - --database-path
      - ${DATABASE_PATH:-./data/app.db}
      - --telegram-token
      - ${TELEGRAM_TOKEN:-telegram_token}
      - --aws-access-key
      - ${AWS_ACCESS_KEY:-aws_access_key}
      - --aws-secret-key
      - ${AWS_SECRET_KEY:-aws_secret_key}
      - --aws-region
      - ${AWS_REGION:-us-east-1}
      - --s3-bucket
      - ${S3_BUCKET:-bucket_name}
      - --s3-endpoint
      - ${S3_ENDPOINT:-s3_endpoint}
      - --s3-protected-bucket
      - ${S3_PROTECTED_BUCKET:-s3_protected_bucket}
      - --aws-protected-access-key
      - ${AWS_PROTECTED_ACCESS_KEY:-aws_protected_access_key}
      - --aws-protected-secret-key
      - ${AWS_PROTECTED_SECRET_KEY:-aws_protected_secret_key}
      - --s3-protected-endpoint
      - ${S3_PROTECTED_ENDPOINT:-s3_protected_endpoint}
      - --faucet-private-key
      - ${FAUCET_PRIVATE_KEY:-faucet_private_key}
      - --rpc-url
      - ${RPC_URL:-rpc_url}
      - --chain-id
      - ${CHAIN_ID:-1}
      - --usdc-contract
      - ${USDC_CONTRACT:-usdc_contract}
      - --payverge-contract
      - ${PAYVERGE_CONTRACT:-payverge_contract}
      - --postmark-server-token
      - ${POSTMARK_SERVER_TOKEN:-postmark_token}
      - --from-email
      - ${FROM_EMAIL:-noreply@yourapp.com}
      - --from-email-news
      - ${FROM_EMAIL_NEWS:-news@yourapp.com}
      - --from-email-updates
      - ${FROM_EMAIL_UPDATES:-updates@yourapp.com}
      - --google-translate-api-key
      - ${GOOGLE_TRANSLATE_API_KEY:-google_translate_api_key}

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
        - ENV_COPY=${ENV_COPY:-production}
        - NEXT_PUBLIC_MAINTENANCE_MODE=${NEXT_PUBLIC_MAINTENANCE_MODE}
        - NEXT_PUBLIC_COMING_SOON_MODE=${NEXT_PUBLIC_COMING_SOON_MODE}
        - NEXT_PUBLIC_PROJECT_ID=${NEXT_PUBLIC_PROJECT_ID}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NEXT_PUBLIC_MAINTENANCE_MODE=${NEXT_PUBLIC_MAINTENANCE_MODE}
      - NEXT_PUBLIC_COMING_SOON_MODE=${NEXT_PUBLIC_COMING_SOON_MODE}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://backend:8080}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL:-ws://backend:8080/ws}
      - NEXT_PUBLIC_ALCHEMY_ID=${NEXT_PUBLIC_ALCHEMY_ID}
      - NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID}
      - NEXT_PUBLIC_PROJECT_ID=${NEXT_PUBLIC_PROJECT_ID}
    networks:
      - server
    depends_on:
      - backend

volumes:
  backend_data:
    driver: local

networks:
  server:
    driver: bridge
