services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PASSWORD=${PASSWORD:-password}
        - USER_NAME=${USER_NAME:-username}
        - URI=${URI:-mongodb://mongodb:27017}
        - AWS_ACCESS_KEY=${AWS_ACCESS_KEY:-aws_access_key}
        - AWS_SECRET_KEY=${AWS_SECRET_KEY:-aws_secret_key}
        - AWS_REGION=${AWS_REGION:-us-east-1}
        - S3_BUCKET=${S3_BUCKET:-bucket_name}
        - S3_ENDPOINT=${S3_ENDPOINT:-s3_endpoint}
        - S3_PROTECTED_BUCKET=${S3_PROTECTED_BUCKET:-s3_protected_bucket}
        - AWS_PROTECTED_ACCESS_KEY=${AWS_PROTECTED_ACCESS_KEY:-aws_protected_access_key}
        - AWS_PROTECTED_SECRET_KEY=${AWS_PROTECTED_SECRET_KEY:-aws_protected_secret_key}
        - S3_PROTECTED_ENDPOINT=${S3_PROTECTED_ENDPOINT:-s3_protected_endpoint}
        - FAUCET_PRIVATE_KEY=${FAUCET_PRIVATE_KEY:-faucet_private_key}
        - RPC_URL=${RPC_URL:-rpc_url}
        - CHAIN_ID=${CHAIN_ID:-chain_id}
    ports:
      - "8080:8080"
    networks:
      - server
    command:
      - --password
      - ${PASSWORD:-password}
      - --username
      - ${USER_NAME:-username}
      - --uri
      - ${URI:-mongodb://mongodb-instance:27017}
      - --telegram-token
      - ${TELEGRAM_TOKEN:-telegram_token}
      - --aws-access-key
      - ${AWS_ACCESS_KEY:-aws_access_key}
      - --aws-secret-key
      - ${AWS_SECRET_KEY:-aws_secret_key}
      - --aws-region
      - ${AWS_REGION:-us-east-1}
      - --s3-bucket
      - ${S3_BUCKET:-bucket_name}
      - --s3-endpoint
      - ${S3_ENDPOINT:-s3_endpoint}
      - --s3-protected-bucket
      - ${S3_PROTECTED_BUCKET:-s3_protected_bucket}
      - --aws-protected-access-key
      - ${AWS_PROTECTED_ACCESS_KEY:-aws_protected_access_key}
      - --aws-protected-secret-key
      - ${AWS_PROTECTED_SECRET_KEY:-aws_protected_secret_key}
      - --s3-protected-endpoint
      - ${S3_PROTECTED_ENDPOINT:-s3_protected_endpoint}
      - --faucet-private-key
      - ${FAUCET_PRIVATE_KEY:-faucet_private_key}
      - --rpc-url
      - ${RPC_URL:-rpc_url}
      - --chain-id
      - ${CHAIN_ID:-1}
      - --usdc-contract
      - ${USDC_CONTRACT:-usdc_contract}
#      - --production
networks:
  server:
    external: true
    name: server
