package server

import "strings"

// waiterItemPlaceholder is substituted with a sanitized menu entity display
// name. A literal placeholder (rather than a printf verb) keeps operator- or
// model-derived names from ever being read as a format string.
const waiterItemPlaceholder = "{item}"

// waiterListPlaceholder is substituted with a comma-joined allergen list from
// the canonical menu snapshot (issue 816). Same literal-replacement rule as
// waiterItemPlaceholder — never a printf verb.
const waiterListPlaceholder = "{list}"

// Check-math placeholders (issue 943). Every substitution comes from the bill
// row's int64-cent total formatted server-side, so — like the placeholders
// above — they are literal strings and never printf verbs.
const (
	waiterPercentPlaceholder = "{percent}"
	waiterAmountPlaceholder  = "{amount}"
	waiterTotalPlaceholder   = "{total}"
	waiterCountPlaceholder   = "{count}"
)

func waiterCopyWithItem(template, displayName string) string {
	if !strings.Contains(template, waiterItemPlaceholder) {
		return template
	}
	return strings.ReplaceAll(template, waiterItemPlaceholder, displayName)
}

// waiterFinalizerCopyByLocale holds the server-owned deterministic waiter copy
// for every guest locale. Before this table existed only en / es / es-AR had
// native copy, so every other locale degraded menu answers to the generic
// "I couldn't find that on the menu" clarification — the waiter could not
// recommend, pair or describe a dish in French, Portuguese, Japanese, etc.
// (issue #577). Keys are canonical guest locale codes; see
// backend/internal/locales/registry_generated.go.
var waiterFinalizerCopyByLocale = map[string]waiterV2Copy{
	"en": {
		recommendIntro:    "Here are some available options from the menu:",
		fullMenuIntro:     "Here is the available menu:",
		available:         "available",
		unavailable:       "unavailable",
		helpAdd:           "I can help add",
		addLabel:          "Add to cart:",
		safeFallback:      "I can help with questions about the menu and your visit.",
		socialReply:       "You're welcome — I'm happy to help.",
		pairingIntro:      "These go well with " + waiterItemPlaceholder + ":",
		alternativesIntro: waiterItemPlaceholder + " is not available right now. These are available instead:",
		pickIntro:         "My pick for you: " + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " goes nicely with it.",
		avoidAllergen:     waiterItemPlaceholder + " lists " + waiterListPlaceholder + ", so I'd skip that one.",
		billTip:           "A " + waiterPercentPlaceholder + "% tip is " + waiterAmountPlaceholder + ". Total with tip: " + waiterTotalPlaceholder + ".",
		billSplit:         "Split " + waiterCountPlaceholder + " ways: " + waiterAmountPlaceholder + " each.",
	},
	"es": {
		recommendIntro:    "Estas son algunas opciones disponibles del menú:",
		fullMenuIntro:     "Este es el menú disponible:",
		available:         "disponible",
		unavailable:       "no disponible",
		helpAdd:           "Puedo ayudarte a agregar",
		addLabel:          "Agregar al carrito:",
		safeFallback:      "Puedo ayudarte con preguntas sobre el menú y tu visita.",
		socialReply:       "De nada — estoy aquí para ayudarte.",
		pairingIntro:      "Estas opciones combinan bien con " + waiterItemPlaceholder + ":",
		alternativesIntro: waiterItemPlaceholder + " no está disponible ahora. Estas opciones sí lo están:",
		pickIntro:         "Mi recomendación: " + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " lo acompaña muy bien.",
		avoidAllergen:     waiterItemPlaceholder + " lleva " + waiterListPlaceholder + ", así que mejor evitarlo.",
		billTip:           "Propina del " + waiterPercentPlaceholder + "%: " + waiterAmountPlaceholder + ". Total con propina: " + waiterTotalPlaceholder + ".",
		billSplit:         "Dividida entre " + waiterCountPlaceholder + ": " + waiterAmountPlaceholder + " por persona.",
	},
	"es-AR": {
		recommendIntro:    "Estas son algunas opciones disponibles del menú:",
		fullMenuIntro:     "Este es el menú disponible:",
		available:         "disponible",
		unavailable:       "no disponible",
		helpAdd:           "Te puedo ayudar a agregar",
		addLabel:          "Agregar al carrito:",
		safeFallback:      "Te puedo ayudar con preguntas sobre el menú y tu visita.",
		socialReply:       "De nada — estoy acá para ayudarte.",
		pairingIntro:      "Estas opciones combinan bien con " + waiterItemPlaceholder + ":",
		alternativesIntro: waiterItemPlaceholder + " no está disponible ahora. Estas opciones sí están disponibles:",
		pickIntro:         "Mi recomendación: " + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " lo acompaña muy bien.",
		avoidAllergen:     waiterItemPlaceholder + " lleva " + waiterListPlaceholder + ", así que mejor evitarlo.",
		billTip:           "Propina del " + waiterPercentPlaceholder + "%: " + waiterAmountPlaceholder + ". Total con propina: " + waiterTotalPlaceholder + ".",
		billSplit:         "Dividida entre " + waiterCountPlaceholder + ": " + waiterAmountPlaceholder + " cada uno.",
	},
	"fr": {
		recommendIntro:    "Voici quelques options disponibles au menu :",
		fullMenuIntro:     "Voici le menu disponible :",
		available:         "disponible",
		unavailable:       "non disponible",
		helpAdd:           "Je peux ajouter",
		addLabel:          "Ajouter au panier :",
		safeFallback:      "Je peux vous aider pour toute question sur le menu et votre visite.",
		socialReply:       "Avec plaisir — je suis là pour vous aider.",
		pairingIntro:      "Ces plats se marient bien avec " + waiterItemPlaceholder + " :",
		alternativesIntro: waiterItemPlaceholder + " n'est pas disponible en ce moment. Ces options le sont :",
		pickIntro:         "Ma suggestion : " + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " l'accompagne très bien.",
		avoidAllergen:     waiterItemPlaceholder + " contient " + waiterListPlaceholder + ", donc je l'éviterais.",
		billTip:           "Pourboire de " + waiterPercentPlaceholder + "% : " + waiterAmountPlaceholder + ". Total avec pourboire : " + waiterTotalPlaceholder + ".",
		billSplit:         "Partagée en " + waiterCountPlaceholder + " : " + waiterAmountPlaceholder + " par personne.",
	},
	"de": {
		recommendIntro:    "Hier sind einige verfügbare Optionen von der Speisekarte:",
		fullMenuIntro:     "Hier ist die verfügbare Speisekarte:",
		available:         "verfügbar",
		unavailable:       "nicht verfügbar",
		helpAdd:           "Ich kann hinzufügen",
		addLabel:          "In den Warenkorb:",
		safeFallback:      "Ich helfe gerne bei Fragen zur Speisekarte und zu Ihrem Besuch.",
		socialReply:       "Gern geschehen — ich helfe Ihnen gerne.",
		pairingIntro:      "Diese passen gut zu " + waiterItemPlaceholder + ":",
		alternativesIntro: waiterItemPlaceholder + " ist gerade nicht verfügbar. Diese Optionen sind verfügbar:",
		pickIntro:         "Meine Empfehlung: " + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " passt gut dazu.",
		avoidAllergen:     waiterItemPlaceholder + " enthält " + waiterListPlaceholder + ", das würde ich auslassen.",
		billTip:           waiterPercentPlaceholder + "% Trinkgeld: " + waiterAmountPlaceholder + ". Gesamt mit Trinkgeld: " + waiterTotalPlaceholder + ".",
		billSplit:         "Auf " + waiterCountPlaceholder + " aufgeteilt: " + waiterAmountPlaceholder + " pro Person.",
	},
	"it": {
		recommendIntro:    "Ecco alcune opzioni disponibili dal menu:",
		fullMenuIntro:     "Ecco il menu disponibile:",
		available:         "disponibile",
		unavailable:       "non disponibile",
		helpAdd:           "Posso aggiungere",
		addLabel:          "Aggiungi al carrello:",
		safeFallback:      "Posso aiutarti con domande sul menu e sulla tua visita.",
		socialReply:       "Di niente — sono qui per aiutarti.",
		pairingIntro:      "Questi si abbinano bene con " + waiterItemPlaceholder + ":",
		alternativesIntro: waiterItemPlaceholder + " non è disponibile al momento. Queste opzioni lo sono:",
		pickIntro:         "Il mio consiglio: " + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " lo accompagna bene.",
		avoidAllergen:     waiterItemPlaceholder + " contiene " + waiterListPlaceholder + ", quindi lo eviterei.",
		billTip:           "Mancia del " + waiterPercentPlaceholder + "%: " + waiterAmountPlaceholder + ". Totale con mancia: " + waiterTotalPlaceholder + ".",
		billSplit:         "Divisa in " + waiterCountPlaceholder + ": " + waiterAmountPlaceholder + " a testa.",
	},
	"pt": {
		recommendIntro:    "Aqui estão algumas opções disponíveis do cardápio:",
		fullMenuIntro:     "Este é o cardápio disponível:",
		available:         "disponível",
		unavailable:       "indisponível",
		helpAdd:           "Posso adicionar",
		addLabel:          "Adicionar ao carrinho:",
		safeFallback:      "Posso ajudar com perguntas sobre o cardápio e sua visita.",
		socialReply:       "De nada — estou aqui para ajudar.",
		pairingIntro:      "Estes combinam bem com " + waiterItemPlaceholder + ":",
		alternativesIntro: waiterItemPlaceholder + " não está disponível agora. Estas opções estão:",
		pickIntro:         "Minha sugestão: " + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " combina bem com ele.",
		avoidAllergen:     waiterItemPlaceholder + " contém " + waiterListPlaceholder + ", então eu evitaria.",
		billTip:           "Gorjeta de " + waiterPercentPlaceholder + "%: " + waiterAmountPlaceholder + ". Total com gorjeta: " + waiterTotalPlaceholder + ".",
		billSplit:         "Dividida por " + waiterCountPlaceholder + ": " + waiterAmountPlaceholder + " por pessoa.",
	},
	"nl": {
		recommendIntro:    "Hier zijn enkele beschikbare opties van het menu:",
		fullMenuIntro:     "Dit is het beschikbare menu:",
		available:         "beschikbaar",
		unavailable:       "niet beschikbaar",
		helpAdd:           "Ik kan toevoegen",
		addLabel:          "Toevoegen aan winkelwagen:",
		safeFallback:      "Ik help graag met vragen over het menu en uw bezoek.",
		socialReply:       "Graag gedaan — ik help u graag.",
		pairingIntro:      "Deze passen goed bij " + waiterItemPlaceholder + ":",
		alternativesIntro: waiterItemPlaceholder + " is nu niet beschikbaar. Deze opties wel:",
		pickIntro:         "Mijn aanrader: " + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " past er goed bij.",
		avoidAllergen:     waiterItemPlaceholder + " bevat " + waiterListPlaceholder + ", dus die zou ik overslaan.",
		billTip:           waiterPercentPlaceholder + "% fooi: " + waiterAmountPlaceholder + ". Totaal met fooi: " + waiterTotalPlaceholder + ".",
		billSplit:         "Verdeeld over " + waiterCountPlaceholder + ": " + waiterAmountPlaceholder + " per persoon.",
	},
	"da": {
		recommendIntro:    "Her er nogle tilgængelige valg fra menuen:",
		fullMenuIntro:     "Her er den tilgængelige menu:",
		available:         "tilgængelig",
		unavailable:       "ikke tilgængelig",
		helpAdd:           "Jeg kan tilføje",
		addLabel:          "Læg i kurv:",
		safeFallback:      "Jeg kan hjælpe med spørgsmål om menuen og dit besøg.",
		socialReply:       "Selv tak — jeg hjælper gerne.",
		pairingIntro:      "Disse passer godt til " + waiterItemPlaceholder + ":",
		alternativesIntro: waiterItemPlaceholder + " er ikke tilgængelig lige nu. Disse er tilgængelige:",
		pickIntro:         "Min anbefaling: " + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " passer godt til.",
		avoidAllergen:     waiterItemPlaceholder + " indeholder " + waiterListPlaceholder + ", så den ville jeg springe over.",
		billTip:           waiterPercentPlaceholder + "% drikkepenge: " + waiterAmountPlaceholder + ". Total med drikkepenge: " + waiterTotalPlaceholder + ".",
		billSplit:         "Delt på " + waiterCountPlaceholder + ": " + waiterAmountPlaceholder + " pr. person.",
	},
	"no": {
		recommendIntro:    "Her er noen tilgjengelige valg fra menyen:",
		fullMenuIntro:     "Her er den tilgjengelige menyen:",
		available:         "tilgjengelig",
		unavailable:       "ikke tilgjengelig",
		helpAdd:           "Jeg kan legge til",
		addLabel:          "Legg i kurv:",
		safeFallback:      "Jeg kan hjelpe med spørsmål om menyen og besøket ditt.",
		socialReply:       "Bare hyggelig — jeg hjelper gjerne.",
		pairingIntro:      "Disse passer godt til " + waiterItemPlaceholder + ":",
		alternativesIntro: waiterItemPlaceholder + " er ikke tilgjengelig nå. Disse er tilgjengelige:",
		pickIntro:         "Min anbefaling: " + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " passer godt til.",
		avoidAllergen:     waiterItemPlaceholder + " inneholder " + waiterListPlaceholder + ", så den ville jeg hoppet over.",
		billTip:           waiterPercentPlaceholder + "% tips: " + waiterAmountPlaceholder + ". Totalt med tips: " + waiterTotalPlaceholder + ".",
		billSplit:         "Delt på " + waiterCountPlaceholder + ": " + waiterAmountPlaceholder + " per person.",
	},
	"sv": {
		recommendIntro:    "Här är några tillgängliga val från menyn:",
		fullMenuIntro:     "Här är den tillgängliga menyn:",
		available:         "tillgänglig",
		unavailable:       "inte tillgänglig",
		helpAdd:           "Jag kan lägga till",
		addLabel:          "Lägg i varukorgen:",
		safeFallback:      "Jag kan hjälpa till med frågor om menyn och ditt besök.",
		socialReply:       "Varsågod — jag hjälper gärna till.",
		pairingIntro:      "Dessa passar bra till " + waiterItemPlaceholder + ":",
		alternativesIntro: waiterItemPlaceholder + " är inte tillgänglig just nu. Dessa är tillgängliga:",
		pickIntro:         "Min rekommendation: " + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " passar bra till.",
		avoidAllergen:     waiterItemPlaceholder + " innehåller " + waiterListPlaceholder + ", så den skulle jag hoppa över.",
		billTip:           waiterPercentPlaceholder + "% dricks: " + waiterAmountPlaceholder + ". Totalt med dricks: " + waiterTotalPlaceholder + ".",
		billSplit:         "Delad på " + waiterCountPlaceholder + ": " + waiterAmountPlaceholder + " per person.",
	},
	"pl": {
		recommendIntro:    "Oto kilka dostępnych pozycji z menu:",
		fullMenuIntro:     "Oto dostępne menu:",
		available:         "dostępne",
		unavailable:       "niedostępne",
		helpAdd:           "Mogę dodać",
		addLabel:          "Dodaj do koszyka:",
		safeFallback:      "Mogę pomóc w pytaniach o menu i Twoją wizytę.",
		socialReply:       "Nie ma za co — chętnie pomogę.",
		pairingIntro:      "Te pozycje dobrze pasują do " + waiterItemPlaceholder + ":",
		alternativesIntro: waiterItemPlaceholder + " jest teraz niedostępne. Te pozycje są dostępne:",
		pickIntro:         "Moja rekomendacja: " + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " dobrze do tego pasuje.",
		avoidAllergen:     waiterItemPlaceholder + " zawiera " + waiterListPlaceholder + ", więc lepiej to pominąć.",
		billTip:           "Napiwek " + waiterPercentPlaceholder + "%: " + waiterAmountPlaceholder + ". Razem z napiwkiem: " + waiterTotalPlaceholder + ".",
		billSplit:         "Podzielone na " + waiterCountPlaceholder + ": " + waiterAmountPlaceholder + " na osobę.",
	},
	"ru": {
		recommendIntro:    "Вот несколько доступных блюд из меню:",
		fullMenuIntro:     "Вот доступное меню:",
		available:         "доступно",
		unavailable:       "недоступно",
		helpAdd:           "Я могу добавить",
		addLabel:          "Добавить в корзину:",
		safeFallback:      "Я могу помочь с вопросами о меню и вашем визите.",
		socialReply:       "Пожалуйста — рад помочь.",
		pairingIntro:      "Это хорошо сочетается с " + waiterItemPlaceholder + ":",
		alternativesIntro: waiterItemPlaceholder + " сейчас недоступно. Доступны эти варианты:",
		pickIntro:         "Моя рекомендация: " + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " хорошо к этому подходит.",
		avoidAllergen:     waiterItemPlaceholder + " содержит " + waiterListPlaceholder + ", так что его лучше пропустить.",
		billTip:           "Чаевые " + waiterPercentPlaceholder + "%: " + waiterAmountPlaceholder + ". Итого с чаевыми: " + waiterTotalPlaceholder + ".",
		billSplit:         "Разделить на " + waiterCountPlaceholder + ": " + waiterAmountPlaceholder + " с человека.",
	},
	"tr": {
		recommendIntro:    "Menüde mevcut olan bazı seçenekler:",
		fullMenuIntro:     "Mevcut menü:",
		available:         "mevcut",
		unavailable:       "mevcut değil",
		helpAdd:           "Şunu ekleyebilirim",
		addLabel:          "Sepete ekle:",
		safeFallback:      "Menü ve ziyaretinizle ilgili sorularda yardımcı olabilirim.",
		socialReply:       "Rica ederim — yardımcı olmaktan memnuniyet duyarım.",
		pairingIntro:      "Bunlar " + waiterItemPlaceholder + " ile iyi gider:",
		alternativesIntro: waiterItemPlaceholder + " şu anda mevcut değil. Bunlar mevcut:",
		pickIntro:         "Önerim: " + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " yanında iyi gider.",
		avoidAllergen:     waiterItemPlaceholder + " içinde " + waiterListPlaceholder + " var, bunu atlardım.",
		billTip:           "%" + waiterPercentPlaceholder + " bahşiş: " + waiterAmountPlaceholder + ". Bahşişle toplam: " + waiterTotalPlaceholder + ".",
		billSplit:         waiterCountPlaceholder + " kişiye bölündü: kişi başı " + waiterAmountPlaceholder + ".",
	},
	"ar": {
		recommendIntro:    "إليك بعض الخيارات المتاحة من القائمة:",
		fullMenuIntro:     "هذه هي القائمة المتاحة:",
		available:         "متاح",
		unavailable:       "غير متاح",
		helpAdd:           "يمكنني إضافة",
		addLabel:          "أضف إلى السلة:",
		safeFallback:      "يمكنني المساعدة في الأسئلة حول القائمة وزيارتك.",
		socialReply:       "على الرحب والسعة — يسعدني مساعدتك.",
		pairingIntro:      "هذه تتناسب جيداً مع " + waiterItemPlaceholder + ":",
		alternativesIntro: waiterItemPlaceholder + " غير متاح حالياً. هذه الخيارات متاحة:",
		pickIntro:         "اقتراحي: " + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " يناسبه جيداً.",
		avoidAllergen:     waiterItemPlaceholder + " يحتوي على " + waiterListPlaceholder + "، لذا أنصح بتجنبه.",
		billTip:           "بقشيش " + waiterPercentPlaceholder + "%: " + waiterAmountPlaceholder + ". الإجمالي مع البقشيش: " + waiterTotalPlaceholder + ".",
		billSplit:         "مقسومة على " + waiterCountPlaceholder + ": " + waiterAmountPlaceholder + " لكل شخص.",
	},
	"hi": {
		recommendIntro:    "मेन्यू से कुछ उपलब्ध विकल्प:",
		fullMenuIntro:     "यह उपलब्ध मेन्यू है:",
		available:         "उपलब्ध",
		unavailable:       "अनुपलब्ध",
		helpAdd:           "मैं जोड़ सकता हूँ",
		addLabel:          "कार्ट में जोड़ें:",
		safeFallback:      "मैं मेन्यू और आपकी विज़िट से जुड़े सवालों में मदद कर सकता हूँ।",
		socialReply:       "आपका स्वागत है — मदद करके खुशी हुई।",
		pairingIntro:      "ये " + waiterItemPlaceholder + " के साथ अच्छे लगते हैं:",
		alternativesIntro: waiterItemPlaceholder + " अभी उपलब्ध नहीं है। ये विकल्प उपलब्ध हैं:",
		pickIntro:         "मेरा सुझाव: " + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " इसके साथ अच्छा लगेगा।",
		avoidAllergen:     waiterItemPlaceholder + " में " + waiterListPlaceholder + " है, इसलिए इसे छोड़ना बेहतर है।",
		billTip:           waiterPercentPlaceholder + "% टिप: " + waiterAmountPlaceholder + ". टिप सहित कुल: " + waiterTotalPlaceholder + ".",
		billSplit:         waiterCountPlaceholder + " लोगों में बाँटें: प्रति व्यक्ति " + waiterAmountPlaceholder + "।",
	},
	"ja": {
		recommendIntro:    "メニューからご用意できる選択肢です:",
		fullMenuIntro:     "ご用意できるメニューです:",
		available:         "提供中",
		unavailable:       "提供不可",
		helpAdd:           "こちらを追加できます:",
		addLabel:          "カートに追加:",
		safeFallback:      "メニューやご来店に関するご質問にお答えできます。",
		socialReply:       "どういたしまして — お手伝いできてうれしいです。",
		pairingIntro:      waiterItemPlaceholder + " によく合うのはこちらです:",
		alternativesIntro: waiterItemPlaceholder + " は現在ご用意できません。こちらはご用意できます:",
		pickIntro:         "おすすめは " + waiterItemPlaceholder + " です",
		pickPairing:       waiterItemPlaceholder + " もよく合います。",
		avoidAllergen:     waiterItemPlaceholder + " には " + waiterListPlaceholder + " が含まれるため、避けたほうがよいでしょう。",
		billTip:           waiterPercentPlaceholder + "%のチップ：" + waiterAmountPlaceholder + "。チップ込みの合計：" + waiterTotalPlaceholder + "。",
		billSplit:         waiterCountPlaceholder + "人で分けると、お一人 " + waiterAmountPlaceholder + "。",
	},
	"ko": {
		recommendIntro:    "메뉴에서 이용 가능한 옵션입니다:",
		fullMenuIntro:     "이용 가능한 메뉴입니다:",
		available:         "이용 가능",
		unavailable:       "이용 불가",
		helpAdd:           "다음을 담아 드릴 수 있어요:",
		addLabel:          "장바구니에 추가:",
		safeFallback:      "메뉴와 방문에 관한 질문을 도와드릴 수 있습니다.",
		socialReply:       "천만에요 — 도와드릴 수 있어 기쁩니다.",
		pairingIntro:      waiterItemPlaceholder + " 와 잘 어울리는 메뉴입니다:",
		alternativesIntro: "지금 " + waiterItemPlaceholder + " 은 이용할 수 없습니다. 다음은 이용 가능합니다:",
		pickIntro:         "제 추천은 " + waiterItemPlaceholder + " 입니다",
		pickPairing:       waiterItemPlaceholder + " 도 잘 어울립니다.",
		avoidAllergen:     waiterItemPlaceholder + " 에는 " + waiterListPlaceholder + " 이(가) 들어 있어 피하는 게 좋겠습니다.",
		billTip:           waiterPercentPlaceholder + "% 팁: " + waiterAmountPlaceholder + ". 팁 포함 합계: " + waiterTotalPlaceholder + ".",
		billSplit:         waiterCountPlaceholder + "명으로 나누면 1인당 " + waiterAmountPlaceholder + ".",
	},
	"th": {
		recommendIntro:    "นี่คือตัวเลือกที่มีให้บริการจากเมนู:",
		fullMenuIntro:     "นี่คือเมนูที่มีให้บริการ:",
		available:         "มีให้บริการ",
		unavailable:       "ไม่มีให้บริการ",
		helpAdd:           "ฉันสามารถเพิ่ม",
		addLabel:          "เพิ่มลงตะกร้า:",
		safeFallback:      "ฉันช่วยตอบคำถามเกี่ยวกับเมนูและการมาใช้บริการของคุณได้",
		socialReply:       "ยินดีค่ะ — ยินดีให้ความช่วยเหลือ",
		pairingIntro:      "รายการเหล่านี้เข้ากันดีกับ " + waiterItemPlaceholder + ":",
		alternativesIntro: waiterItemPlaceholder + " ไม่มีให้บริการในขณะนี้ รายการเหล่านี้มีให้บริการ:",
		pickIntro:         "ที่ฉันแนะนำคือ " + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " เข้ากันได้ดี",
		avoidAllergen:     waiterItemPlaceholder + " มี " + waiterListPlaceholder + " จึงแนะนำให้เลี่ยง",
		billTip:           "ทิป " + waiterPercentPlaceholder + "%: " + waiterAmountPlaceholder + " รวมทิปทั้งหมด: " + waiterTotalPlaceholder,
		billSplit:         "หาร " + waiterCountPlaceholder + " คน: คนละ " + waiterAmountPlaceholder,
	},
	"vi": {
		recommendIntro:    "Đây là một số lựa chọn có sẵn trong thực đơn:",
		fullMenuIntro:     "Đây là thực đơn hiện có:",
		available:         "có sẵn",
		unavailable:       "không có sẵn",
		helpAdd:           "Tôi có thể thêm",
		addLabel:          "Thêm vào giỏ:",
		safeFallback:      "Tôi có thể giúp bạn với các câu hỏi về thực đơn và chuyến ghé thăm của bạn.",
		socialReply:       "Không có gì — tôi rất vui được giúp.",
		pairingIntro:      "Những món này hợp với " + waiterItemPlaceholder + ":",
		alternativesIntro: waiterItemPlaceholder + " hiện không có sẵn. Những món này thì có:",
		pickIntro:         "Gợi ý của tôi: " + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " rất hợp để dùng kèm.",
		avoidAllergen:     waiterItemPlaceholder + " có " + waiterListPlaceholder + ", nên tôi sẽ bỏ qua món đó.",
		billTip:           "Tiền boa " + waiterPercentPlaceholder + "%: " + waiterAmountPlaceholder + ". Tổng gồm tiền boa: " + waiterTotalPlaceholder + ".",
		billSplit:         "Chia cho " + waiterCountPlaceholder + " người: " + waiterAmountPlaceholder + " mỗi người.",
	},
	"zh": {
		recommendIntro:    "以下是菜单上可供选择的菜品：",
		fullMenuIntro:     "以下是可供选择的菜单：",
		available:         "可供应",
		unavailable:       "暂不供应",
		helpAdd:           "我可以为您添加",
		addLabel:          "加入购物车：",
		safeFallback:      "我可以回答有关菜单和您用餐的问题。",
		socialReply:       "不客气 — 很高兴为您服务。",
		pairingIntro:      "这些与 " + waiterItemPlaceholder + " 很搭：",
		alternativesIntro: waiterItemPlaceholder + " 目前不可用。以下菜品可供选择：",
		pickIntro:         "我的推荐：" + waiterItemPlaceholder,
		pickPairing:       waiterItemPlaceholder + " 很适合搭配。",
		avoidAllergen:     waiterItemPlaceholder + " 含有 " + waiterListPlaceholder + "，建议避开。",
		billTip:           waiterPercentPlaceholder + "% 小费：" + waiterAmountPlaceholder + "。含小费合计：" + waiterTotalPlaceholder + "。",
		billSplit:         "分成 " + waiterCountPlaceholder + " 份：每人 " + waiterAmountPlaceholder + "。",
	},
}

// waiterFinalizerCopy returns the server-owned deterministic copy for a
// canonical guest locale, falling back to English for anything unrecognized.
func waiterFinalizerCopy(locale string) waiterV2Copy {
	if copy, ok := waiterFinalizerCopyByLocale[locale]; ok {
		return copy
	}
	if copy, ok := waiterFinalizerCopyByLocale[normalizeWaiterMenuSnapshotLocale(locale, "")]; ok {
		return copy
	}
	return waiterFinalizerCopyByLocale["en"]
}

// waiterNativeSmallTalkLocale gates the untrusted-prose paths (validated jokes
// and the social reply). Menu answers are fully server-owned in every locale,
// but model prose is only re-checked against en / es forbidden-phrase
// vocabularies, so passing it through in other locales would weaken the
// no-model-facts guarantee.
func waiterNativeSmallTalkLocale(locale string) bool {
	return locale == "en" || locale == "es" || locale == "es-AR"
}
