package server

import (
	"strings"

	"github.com/stdevmac/payverge/backend/internal/locales"
)

// Issue 875: menu allergen chips are stored as canonical English ids ("eggs",
// "dairy", "so2"), so a Spanish allergen answer read "Empanada de carne: gluten,
// eggs." — the venue's own language broken by an untranslated data token. This
// table is the Go mirror of the guest UI's menu.allergenNames (one entry per
// guest locale, generated from frontend/src/i18n/guest-messages/*.json), so the
// waiter names an allergen exactly the way the chip on the guest's card does.
//
// Operator free-text allergens are NOT in this table and are passed through
// unchanged: a value we cannot translate must still reach the guest verbatim.
var waiterAllergenLabelsByLocale = map[string]map[string]string{
	"ar": {
		"celery":      "الكرفس",
		"crustaceans": "القشريات",
		"dairy":       "منتجات الألبان",
		"eggs":        "بيض",
		"fish":        "سمك",
		"gluten":      "الغلوتين",
		"lupin":       "الترمس",
		"mollusc":     "الرخويات",
		"mustard":     "الخردل",
		"peanut":      "الفول السوداني",
		"sesame":      "السمسم",
		"so2":         "ثاني أكسيد الكبريت",
		"soya":        "صويا",
		"treenuts":    "المكسرات",
	},
	"da": {
		"celery":      "Selleri",
		"crustaceans": "Skaldyr",
		"dairy":       "Mejeriprodukter",
		"eggs":        "Æg",
		"fish":        "Fisk",
		"gluten":      "Gluten",
		"lupin":       "Lupin",
		"mollusc":     "Bløddyr",
		"mustard":     "Sennep",
		"peanut":      "Jordnødder",
		"sesame":      "Sesam",
		"so2":         "Svovldioxid",
		"soya":        "Soja",
		"treenuts":    "Trænødder",
	},
	"de": {
		"celery":      "Sellerie",
		"crustaceans": "Krebstiere",
		"dairy":       "Milchprodukte",
		"eggs":        "Eier",
		"fish":        "Fisch",
		"gluten":      "Gluten",
		"lupin":       "Lupinen",
		"mollusc":     "Weichtiere",
		"mustard":     "Senf",
		"peanut":      "Erdnüsse",
		"sesame":      "Sesam",
		"so2":         "Schwefeldioxid",
		"soya":        "Soja",
		"treenuts":    "Schalenfrüchte",
	},
	"en": {
		"celery":      "Celery",
		"crustaceans": "Crustaceans",
		"dairy":       "Dairy",
		"eggs":        "Eggs",
		"fish":        "Fish",
		"gluten":      "Gluten",
		"lupin":       "Lupin",
		"mollusc":     "Mollusc",
		"mustard":     "Mustard",
		"peanut":      "Peanut",
		"sesame":      "Sesame",
		"so2":         "Sulphur Dioxide",
		"soya":        "Soya",
		"treenuts":    "Tree Nuts",
	},
	"es": {
		"celery":      "Apio",
		"crustaceans": "Crustáceos",
		"dairy":       "Lácteos",
		"eggs":        "Huevos",
		"fish":        "Pescado",
		"gluten":      "Gluten",
		"lupin":       "Altramuces",
		"mollusc":     "Moluscos",
		"mustard":     "Mostaza",
		"peanut":      "Cacahuetes",
		"sesame":      "Sésamo",
		"so2":         "Dióxido de azufre",
		"soya":        "Soja",
		"treenuts":    "Frutos de cáscara",
	},
	"es-AR": {
		"celery":      "Apio",
		"crustaceans": "Crustáceos",
		"dairy":       "Lácteos",
		"eggs":        "Huevos",
		"fish":        "Pescado",
		"gluten":      "Gluten",
		"lupin":       "Altramuces",
		"mollusc":     "Moluscos",
		"mustard":     "Mostaza",
		"peanut":      "Cacahuetes",
		"sesame":      "Sésamo",
		"so2":         "Dióxido de azufre",
		"soya":        "Soja",
		"treenuts":    "Frutos de cáscara",
	},
	"fr": {
		"celery":      "Céleri",
		"crustaceans": "Crustacés",
		"dairy":       "Produits laitiers",
		"eggs":        "Œufs",
		"fish":        "Poisson",
		"gluten":      "Gluten",
		"lupin":       "Lupin",
		"mollusc":     "Mollusque",
		"mustard":     "Moutarde",
		"peanut":      "Arachide",
		"sesame":      "Sésame",
		"so2":         "Dioxyde de soufre",
		"soya":        "Soja",
		"treenuts":    "Fruits à coque",
	},
	"hi": {
		"celery":      "सेलेरी",
		"crustaceans": "क्रस्टेशियन",
		"dairy":       "डेयरी",
		"eggs":        "अंडे",
		"fish":        "मछली",
		"gluten":      "ग्लूटेन",
		"lupin":       "ल्यूपिन",
		"mollusc":     "मोलस्क",
		"mustard":     "सरसों",
		"peanut":      "मूंगफली",
		"sesame":      "तिल",
		"so2":         "सल्फर डाइऑक्साइड",
		"soya":        "सोया",
		"treenuts":    "ट्री नट्स",
	},
	"it": {
		"celery":      "Sedano",
		"crustaceans": "Crostacei",
		"dairy":       "Latticini",
		"eggs":        "Uova",
		"fish":        "Pesce",
		"gluten":      "Glutine",
		"lupin":       "Lupini",
		"mollusc":     "Molluschi",
		"mustard":     "Senape",
		"peanut":      "Arachidi",
		"sesame":      "Sesamo",
		"so2":         "Anidride solforosa",
		"soya":        "Soia",
		"treenuts":    "Frutta a guscio",
	},
	"ja": {
		"celery":      "セロリ",
		"crustaceans": "甲殻類",
		"dairy":       "乳製品",
		"eggs":        "卵",
		"fish":        "魚",
		"gluten":      "グルテン",
		"lupin":       "ルピナス豆",
		"mollusc":     "軟体動物",
		"mustard":     "マスタード",
		"peanut":      "ピーナッツ",
		"sesame":      "ごま",
		"so2":         "二酸化硫黄",
		"soya":        "大豆",
		"treenuts":    "木の実",
	},
	"ko": {
		"celery":      "셀러리",
		"crustaceans": "갑각류",
		"dairy":       "유제품",
		"eggs":        "달걀",
		"fish":        "생선",
		"gluten":      "글루텐",
		"lupin":       "루핀",
		"mollusc":     "연체동물",
		"mustard":     "겨자",
		"peanut":      "땅콩",
		"sesame":      "참깨",
		"so2":         "이산화황",
		"soya":        "대두",
		"treenuts":    "견과류",
	},
	"nl": {
		"celery":      "Selderij",
		"crustaceans": "Schaaldieren",
		"dairy":       "Zuivel",
		"eggs":        "Eieren",
		"fish":        "Vis",
		"gluten":      "Gluten",
		"lupin":       "Lupine",
		"mollusc":     "Weekdieren",
		"mustard":     "Mosterd",
		"peanut":      "Pinda",
		"sesame":      "Sesam",
		"so2":         "Zwaveldioxide",
		"soya":        "Soja",
		"treenuts":    "Noten",
	},
	"no": {
		"celery":      "Selleri",
		"crustaceans": "Skalldyr",
		"dairy":       "Meieriprodukter",
		"eggs":        "Egg",
		"fish":        "Fisk",
		"gluten":      "Gluten",
		"lupin":       "Lupin",
		"mollusc":     "Bløtdyr",
		"mustard":     "Sennep",
		"peanut":      "Peanøtter",
		"sesame":      "Sesam",
		"so2":         "Svoveldioksid",
		"soya":        "Soya",
		"treenuts":    "Trenøtter",
	},
	"pl": {
		"celery":      "Seler",
		"crustaceans": "Skorupiaki",
		"dairy":       "Nabiał",
		"eggs":        "Jaja",
		"fish":        "Ryba",
		"gluten":      "Gluten",
		"lupin":       "Łubin",
		"mollusc":     "Mięczaki",
		"mustard":     "Gorczyca",
		"peanut":      "Orzeszki ziemne",
		"sesame":      "Sezam",
		"so2":         "Dwutlenek siarki",
		"soya":        "Soja",
		"treenuts":    "Orzechy",
	},
	"pt": {
		"celery":      "Aipo",
		"crustaceans": "Crustáceos",
		"dairy":       "Laticínios",
		"eggs":        "Ovos",
		"fish":        "Peixe",
		"gluten":      "Glúten",
		"lupin":       "Tremoço",
		"mollusc":     "Moluscos",
		"mustard":     "Mostarda",
		"peanut":      "Amendoim",
		"sesame":      "Gergelim",
		"so2":         "Dióxido de enxofre",
		"soya":        "Soja",
		"treenuts":    "Castanhas",
	},
	"ru": {
		"celery":      "Сельдерей",
		"crustaceans": "Ракообразные",
		"dairy":       "Молочные продукты",
		"eggs":        "Яйца",
		"fish":        "Рыба",
		"gluten":      "Глютен",
		"lupin":       "Люпин",
		"mollusc":     "Моллюски",
		"mustard":     "Горчица",
		"peanut":      "Арахис",
		"sesame":      "Кунжут",
		"so2":         "Диоксид серы",
		"soya":        "Соя",
		"treenuts":    "Орехи",
	},
	"sv": {
		"celery":      "Selleri",
		"crustaceans": "Skaldjur",
		"dairy":       "Mejeriprodukter",
		"eggs":        "Ägg",
		"fish":        "Fisk",
		"gluten":      "Gluten",
		"lupin":       "Lupin",
		"mollusc":     "Blötdjur",
		"mustard":     "Senap",
		"peanut":      "Jordnötter",
		"sesame":      "Sesam",
		"so2":         "Svaveldioxid",
		"soya":        "Soja",
		"treenuts":    "Trädnötter",
	},
	"th": {
		"celery":      "ขึ้นฉ่าย",
		"crustaceans": "สัตว์น้ำที่มีเปลือกแข็ง",
		"dairy":       "ผลิตภัณฑ์นม",
		"eggs":        "ไข่",
		"fish":        "ปลา",
		"gluten":      "กลูเตน",
		"lupin":       "ลูปิน",
		"mollusc":     "สัตว์จำพวกหอยและปลาหมึก",
		"mustard":     "มัสตาร์ด",
		"peanut":      "ถั่วลิงสง",
		"sesame":      "งา",
		"so2":         "ซัลเฟอร์ไดออกไซด์",
		"soya":        "ถั่วเหลือง",
		"treenuts":    "ถั่วเปลือกแข็ง",
	},
	"tr": {
		"celery":      "Kereviz",
		"crustaceans": "Kabuklular",
		"dairy":       "Süt Ürünleri",
		"eggs":        "Yumurta",
		"fish":        "Balık",
		"gluten":      "Gluten",
		"lupin":       "Acı Bakla",
		"mollusc":     "Yumuşakçalar",
		"mustard":     "Hardal",
		"peanut":      "Yer Fıstığı",
		"sesame":      "Susam",
		"so2":         "Sülfür Dioksit",
		"soya":        "Soya",
		"treenuts":    "Sert Kabuklu Yemişler",
	},
	"vi": {
		"celery":      "Cần tây",
		"crustaceans": "Giáp xác",
		"dairy":       "Sữa",
		"eggs":        "Trứng",
		"fish":        "Cá",
		"gluten":      "Gluten",
		"lupin":       "Đậu lupin",
		"mollusc":     "Nhuyễn thể",
		"mustard":     "Mù tạt",
		"peanut":      "Đậu phộng",
		"sesame":      "Vừng",
		"so2":         "Lưu huỳnh dioxide",
		"soya":        "Đậu nành",
		"treenuts":    "Hạt cây",
	},
	"zh": {
		"celery":      "芹菜",
		"crustaceans": "甲壳类",
		"dairy":       "乳制品",
		"eggs":        "蛋类",
		"fish":        "鱼类",
		"gluten":      "麸质",
		"lupin":       "羽扇豆",
		"mollusc":     "软体动物",
		"mustard":     "芥末",
		"peanut":      "花生",
		"sesame":      "芝麻",
		"so2":         "二氧化硫",
		"soya":        "大豆",
		"treenuts":    "坚果",
	},
}

// waiterAllergenLabel translates one canonical allergen id into the guest's
// locale. Unknown ids (operator free text) come back trimmed but unchanged.
func waiterAllergenLabel(locale, allergen string) string {
	trimmed := strings.TrimSpace(allergen)
	if trimmed == "" {
		return ""
	}
	key := strings.NewReplacer(" ", "", "-", "", "_", "").Replace(strings.ToLower(trimmed))
	table, ok := waiterAllergenLabelsByLocale[locale]
	if !ok {
		if resolved, found := locales.Lookup(locale); found {
			table = waiterAllergenLabelsByLocale[resolved.Canonical]
		}
	}
	if table == nil {
		table = waiterAllergenLabelsByLocale["en"]
	}
	if label, found := table[key]; found {
		return label
	}
	return trimmed
}

// waiterLocalizedAllergens maps a dish's allergen chips into the guest's
// locale, preserving order and dropping blanks.
func waiterLocalizedAllergens(locale string, allergens []string) []string {
	out := make([]string, 0, len(allergens))
	for _, allergen := range allergens {
		if label := waiterAllergenLabel(locale, allergen); label != "" {
			out = append(out, label)
		}
	}
	return out
}
