package database

import (
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func migrateDirectorProposedActionTables(t *testing.T) {
	t.Helper()
	require.NoError(t, db.AutoMigrate(&DirectorProposedAction{}, &DirectorActionAudit{}))
}

func TestDirectorProposedAction_CreateAndGetByPublicID(t *testing.T) {
	setupTestDB(t)
	migrateDirectorProposedActionTables(t)

	p := &DirectorProposedAction{
		PublicID:    "pa_test123",
		BusinessID:  7,
		ThreadID:    3,
		Kind:        "menu.adjust_prices",
		ParamsJSON:  `{"scope":"all","mode":"percent","value":20,"direction":"up"}`,
		PreviewJSON: `{"affected_count":2}`,
		MenuVersion: 5,
		Status:      DirectorProposalPending,
		ExpiresAt:   time.Now().Add(time.Hour),
	}
	if err := CreateDirectorProposedAction(p); err != nil {
		t.Fatalf("create: %v", err)
	}
	if p.ID == 0 {
		t.Fatal("expected autogenerated ID")
	}
	got, err := GetDirectorProposedActionByPublicID(7, "pa_test123")
	if err != nil {
		t.Fatalf("get: %v", err)
	}
	if got.MenuVersion != 5 || got.Status != DirectorProposalPending {
		t.Fatalf("round-trip mismatch: %+v", got)
	}
	// scoped: wrong business → not found
	if _, err := GetDirectorProposedActionByPublicID(8, "pa_test123"); err == nil {
		t.Fatal("expected not-found for wrong business scope")
	}
}

func TestDirectorProposedAction_DismissBatch(t *testing.T) {
	setupTestDB(t)
	migrateDirectorProposedActionTables(t)

	// Create two pending rows.
	p1 := &DirectorProposedAction{
		BusinessID:  10,
		ThreadID:    1,
		Kind:        "menu.adjust_prices",
		ParamsJSON:  `{}`,
		PreviewJSON: `{}`,
		MenuVersion: 1,
		Status:      DirectorProposalPending,
		ExpiresAt:   time.Now().Add(time.Hour),
	}
	p2 := &DirectorProposedAction{
		BusinessID:  10,
		ThreadID:    1,
		Kind:        "menu.adjust_prices",
		ParamsJSON:  `{}`,
		PreviewJSON: `{}`,
		MenuVersion: 1,
		Status:      DirectorProposalPending,
		ExpiresAt:   time.Now().Add(time.Hour),
	}
	require.NoError(t, CreateDirectorProposedAction(p1))
	require.NoError(t, CreateDirectorProposedAction(p2))

	// Dismiss batch.
	require.NoError(t, DismissDirectorProposals([]uint{p1.ID, p2.ID}))

	// Both should now be dismissed.
	got1, err := GetDirectorProposedActionByPublicID(10, p1.PublicID)
	require.NoError(t, err)
	if got1.Status != DirectorProposalDismissed {
		t.Fatalf("expected dismissed, got %q", got1.Status)
	}
	got2, err := GetDirectorProposedActionByPublicID(10, p2.PublicID)
	require.NoError(t, err)
	if got2.Status != DirectorProposalDismissed {
		t.Fatalf("expected dismissed, got %q", got2.Status)
	}
}

func TestNewDirectorActionPublicID_UniquePrefixed(t *testing.T) {
	a := newDirectorActionPublicID()
	b := newDirectorActionPublicID()
	if a == b {
		t.Fatal("expected distinct ids")
	}
	if !strings.HasPrefix(a, "pa_") || len(a) < 20 {
		t.Fatalf("bad public id %q", a)
	}
}

func TestDirectorProposedAction_AttachMessageID(t *testing.T) {
	setupTestDB(t)
	migrateDirectorProposedActionTables(t)

	p := &DirectorProposedAction{
		BusinessID:  30,
		ThreadID:    7,
		Kind:        "menu.adjust_prices",
		ParamsJSON:  `{}`,
		PreviewJSON: `{}`,
		MenuVersion: 1,
		Status:      DirectorProposalPending,
		ExpiresAt:   time.Now().Add(time.Hour),
	}
	require.NoError(t, CreateDirectorProposedAction(p))

	require.NoError(t, AttachMessageIDToProposals([]uint{p.ID}, 555))

	got, err := GetDirectorProposedActionByPublicID(30, p.PublicID)
	require.NoError(t, err)
	if got.MessageID == nil || *got.MessageID != 555 {
		t.Fatalf("expected message_id=555, got %v", got.MessageID)
	}
}
