#!/usr/bin/env node
/**
 * Builds the two inputs the /design-sync converter needs from this repo:
 *
 *   1. dist/**\/*.d.ts  — declaration-only tsc emit over ds/index.tsx. These are
 *      the prop contracts the claude.ai/design agent codes against, so they
 *      must come from the app's real types, not be hand-written.
 *   2. styles.css       — the app's Tailwind theme compiled to a static
 *      stylesheet (the app compiles it at `next build` time; the bundle has no
 *      build step of its own).
 *
 * Run from anywhere: node frontend/ds/build.mjs
 * Run it before every design-bundle sync.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const DS = dirname(fileURLToPath(import.meta.url));
const FRONTEND = resolve(DS, "..");

// Regenerate the asset shim from the real public/ asset. See asset-shim.css
// for why the brand mark has to be inlined for the design environment.
const LOGO = join(FRONTEND, "public/images/PayvergeLogo.png");
writeFileSync(
  join(DS, "asset-shim.css"),
  `/* GENERATED by ds/build.mjs from public/images/PayvergeLogo.png — do not edit.
 *
 * TopMenuShell / TopMenuInstantChrome render the brand mark with next/image at
 * the ROOT-ABSOLUTE path /images/PayvergeLogo.png, which only resolves against
 * the Next app's public/ directory. Outside the app — in a preview card, and in
 * any design built with these components — that request 404s and the nav shows
 * a broken image. Inlining the real bytes keeps the mark correct everywhere.
 */
img[src="/images/PayvergeLogo.png"] {
  content: url("data:image/png;base64,${readFileSync(LOGO).toString("base64")}");
}
`,
);
process.stderr.write("» asset-shim.css regenerated from public/images/PayvergeLogo.png\n");

const run = (label, args, cwd) => {
  process.stderr.write(`» ${label}\n`);
  execFileSync("npx", args, { cwd, stdio: "inherit" });
};

// tsc resolves ../tsconfig.json's `paths` itself; run it from ds/.
run("tsc --emitDeclarationOnly", ["tsc", "-p", "tsconfig.json"], DS);

// Tailwind resolves `content` globs relative to CWD — run from frontend/.
run(
  "tailwindcss -> ds/styles.css",
  [
    "tailwindcss",
    "-c", "ds/tailwind.config.ts",
    "-i", "ds/styles.src.css",
    "-o", "ds/styles.css",
    "--minify",
  ],
  FRONTEND,
);

process.stderr.write("✓ ds build complete\n");
