import {
  addMenuCategory,
  addMenuItem,
  createBusiness,
  updateBusiness,
  updateMenuCategory,
  updateMenuItem,
  enhanceMenuItemImage,
  generateMenuImage,
  regenerateMenuItemImage,
  importExtractedMenu,
  type Business,
  type CreateBusinessRequest,
} from "@/api/business";
import { axiosInstance } from "@/api/tools/instance";
import { asDollars } from "@/types/money";

jest.mock("@/api/tools/instance", () => ({
  axiosInstance: {
    get: jest.fn(),
    put: jest.fn(),
    post: jest.fn(),
  },
}));

jest.mock("@/utils/errorLogger", () => ({
  logError: jest.fn(),
}));

describe("business api", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it("creates a workspace directly without a registration checkout payload", async () => {
    const request: CreateBusinessRequest = {
      name: "Café Luna",
      address: {
        street: "1 Main Street",
        city: "Dubai",
        state: "Dubai",
        postal_code: "00000",
        country: "AE",
      },
      settlement_address: "",
      tipping_address: "",
      tax_rate: 0,
      service_fee_rate: 0,
      tax_inclusive: false,
      service_inclusive: false,
      default_currency: "AED",
      display_currency: "AED",
      timezone: "Asia/Dubai",
    };
    const response: Business = {
      id: 42,
      business_id: "cafe-luna",
      owner_address: "",
      name: "Café Luna",
      logo: "",
      address: request.address,
      settlement_address: "",
      tipping_address: "",
      tax_rate: 0,
      service_fee_rate: 0,
      tax_inclusive: false,
      service_inclusive: false,
      is_active: true,
      created_at: "2026-07-31T00:00:00Z",
      updated_at: "2026-07-31T00:00:00Z",
    };
    (axiosInstance.post as jest.Mock).mockResolvedValue({ data: response });

    await expect(createBusiness(request)).resolves.toEqual(response);
    expect(axiosInstance.post).toHaveBeenCalledWith(
      "/inside/businesses",
      request,
    );
  });

  it("posts the chosen image url to the enhance endpoint", async () => {
    (axiosInstance.post as jest.Mock).mockResolvedValue({
      data: { url: "https://x/enhanced.png", credit: "Enhanced by AI" },
    });

    const result = await enhanceMenuItemImage(42, "https://x/a.png", "Burger", "Beef");

    expect(axiosInstance.post).toHaveBeenCalledWith(
      "/inside/businesses/42/ai/enhance-image",
      { image_url: "https://x/a.png", item_name: "Burger", item_description: "Beef" },
    );
    expect(result.url).toBe("https://x/enhanced.png");
  });

  it("sends dietary tags on generate-menu-image so breakdowns keep dietary safety (#588)", async () => {
    (axiosInstance.post as jest.Mock).mockResolvedValue({
      data: { url: "https://x/breakdown.jpg", credit: "Generated by AI" },
    });

    await generateMenuImage(42, {
      name: "Harvest Bowl",
      description: "Roasted vegetables, grains, herbs",
      ingredients: "Roasted vegetables, grains, herbs",
      dietary_tags: ["vegetarian"],
    });

    expect(axiosInstance.post).toHaveBeenCalledWith(
      "/inside/businesses/42/generate-menu-image",
      {
        name: "Harvest Bowl",
        description: "Roasted vegetables, grains, herbs",
        ingredients: "Roasted vegetables, grains, herbs",
        dietary_tags: ["vegetarian"],
      },
    );
  });

  it("sends dietary tags to the enhance endpoint so the prompt keeps dietary safety (#601)", async () => {
    (axiosInstance.post as jest.Mock).mockResolvedValue({
      data: { url: "https://x/enhanced.png", credit: "Enhanced by AI" },
    });

    await enhanceMenuItemImage(42, "https://x/a.png", "Harvest Bowl", "Veg", [
      "vegetarian",
    ]);

    expect(axiosInstance.post).toHaveBeenCalledWith(
      "/inside/businesses/42/ai/enhance-image",
      {
        image_url: "https://x/a.png",
        item_name: "Harvest Bowl",
        item_description: "Veg",
        dietary_tags: ["vegetarian"],
      },
    );
  });

  it("sends dietary tags to the regenerate endpoint and omits the field when absent (#601)", async () => {
    (axiosInstance.post as jest.Mock).mockResolvedValue({
      data: { url: "https://x/regen.png", credit: "Generated by AI" },
    });

    await regenerateMenuItemImage(42, "Harvest Bowl", "Veg", "moodier", [
      "vegan",
    ]);
    expect(axiosInstance.post).toHaveBeenCalledWith(
      "/inside/businesses/42/ai/regenerate-image",
      {
        item_name: "Harvest Bowl",
        item_description: "Veg",
        custom_prompt: "moodier",
        dietary_tags: ["vegan"],
      },
    );

    await regenerateMenuItemImage(42, "Burger", "Beef", "moodier");
    expect(axiosInstance.post).toHaveBeenLastCalledWith(
      "/inside/businesses/42/ai/regenerate-image",
      {
        item_name: "Burger",
        item_description: "Beef",
        custom_prompt: "moodier",
      },
    );
  });

  it("sends an explicit sanitization confirmation on the second menu import request", async () => {
    const response = {
      message: "Menu imported successfully",
      requires_confirmation: false,
      sanitization: {
        dropped_allergens: 0,
        dropped_dietary_tags: 0,
        dropped_items: 0,
        retained: [],
        dropped: [],
      },
    };
    (axiosInstance.post as jest.Mock).mockResolvedValue({ data: response });
    const categories = [{ name: "Mains", description: "", items: [] }];

    await importExtractedMenu(42, categories, "USD", true);

    expect(axiosInstance.post).toHaveBeenCalledWith(
      "/inside/businesses/42/ai/import-extracted-menu",
      {
        categories,
        currency: "USD",
        confirm_sanitization: true,
      },
    );
  });

  // L3-4: plate COGS must leave the browser on create + update.
  it("includes cogs on addMenuItem and updateMenuItem payloads", async () => {
    (axiosInstance.post as jest.Mock).mockResolvedValue({ data: { message: "ok" } });
    (axiosInstance.put as jest.Mock).mockResolvedValue({ data: { message: "ok" } });
    const item = {
      id: "item-1",
      name: "Taco",
      description: "",
      price: asDollars(12),
      cogs: asDollars(3.5),
      currency: "USD",
      is_available: true,
    };

    await addMenuItem(42, 0, item, 3, "cat-1", true);
    await updateMenuItem(42, 0, 0, item, 3, "cat-1", "item-1", true);

    expect(axiosInstance.post).toHaveBeenCalledWith(
      "/inside/businesses/42/menu/items",
      expect.objectContaining({
        item: expect.objectContaining({ cogs: asDollars(3.5), name: "Taco" }),
      }),
    );
    expect(axiosInstance.put).toHaveBeenCalledWith(
      "/inside/businesses/42/menu/items",
      expect.objectContaining({
        item: expect.objectContaining({ cogs: asDollars(3.5), name: "Taco" }),
      }),
    );
  });

  it("sends explicit sanitization confirmation for every manual menu write", async () => {
    (axiosInstance.post as jest.Mock).mockResolvedValue({ data: { message: "ok" } });
    (axiosInstance.put as jest.Mock).mockResolvedValue({ data: { message: "ok" } });
    const category = { id: "cat-1", name: "Mains", description: "", items: [] };
    const item = {
      id: "item-1",
      name: "Taco",
      description: "",
      price: asDollars(12),
      currency: "USD",
      is_available: true,
    };

    await addMenuCategory(42, category, 3, true);
    await updateMenuCategory(42, 0, category, 3, "cat-1", true);
    await addMenuItem(42, 0, item, 3, "cat-1", true);
    await updateMenuItem(42, 0, 0, item, 3, "cat-1", "item-1", true);

    expect(axiosInstance.post).toHaveBeenNthCalledWith(
      1,
      "/inside/businesses/42/menu/categories",
      expect.objectContaining({ confirm_sanitization: true }),
    );
    expect(axiosInstance.put).toHaveBeenNthCalledWith(
      1,
      "/inside/businesses/42/menu/category/cat-1",
      expect.objectContaining({ confirm_sanitization: true }),
    );
    expect(axiosInstance.post).toHaveBeenNthCalledWith(
      2,
      "/inside/businesses/42/menu/items",
      expect.objectContaining({ confirm_sanitization: true }),
    );
    expect(axiosInstance.put).toHaveBeenNthCalledWith(
      2,
      "/inside/businesses/42/menu/items",
      expect.objectContaining({ confirm_sanitization: true }),
    );
  });

  it("does not send delivery settings through the generic business update route", async () => {
    (axiosInstance.put as jest.Mock).mockResolvedValue({
      data: {
        id: 42,
        owner_address: "0xowner",
        name: "Core Cafe",
        logo: "",
        address: {
          street: "",
          city: "",
          state: "",
          postal_code: "",
          country: "",
        },
        settlement_address: "0xsettlement",
        tipping_address: "0xtipping",
        tax_rate: 0,
        service_fee_rate: 0,
        tax_inclusive: false,
        service_inclusive: false,
        is_active: true,
        created_at: "2026-05-01T00:00:00Z",
        updated_at: "2026-05-01T00:00:00Z",
      },
    });

    // L3-39: delivery_radius is no longer part of any delivery contract, so it
    // is not in the strip list either — the keys below are the live ones.
    await updateBusiness(42, {
      name: "Core Cafe",
      delivery_enabled: true,
      delivery_instructions: "Leave at counter",
    } as never);

    expect(axiosInstance.put).toHaveBeenCalledWith("/inside/businesses/42", {
      name: "Core Cafe",
    });
  });
});
