import {
  getMarketingSuggestions,
  getMarketingSuggestionsWithState,
  generateMarketingImage,
  cleanupMarketingImage,
  generateMarketingCaption,
  getMarketingActivity,
  recordMarketingActivity,
  restoreMarketingActivity,
  getMarketingSettings,
  isMarketingPlay,
  updateMarketingSettings,
  ImageDailyLimitError,
  PromptRejectedError,
} from "@/api/marketing";
import type {
  CampaignSuggestion,
  GenerateMarketingCaptionRequest,
  GenerateMarketingImageRequest,
  MarketingActivity,
  MarketingActivityPlay,
  MarketingActivityFilters,
  MarketingActivitySnapshot,
  MarketingCreativeProfile,
  MarketingCreativeSnapshot,
  MarketingPlay,
  MarketingSettings,
} from "@/api/marketing";
import { axiosInstance } from "@/api/tools/instance";

jest.mock("@/api/tools/instance", () => ({
  axiosInstance: { get: jest.fn(), post: jest.fn(), put: jest.fn() },
}));

const mockGet = axiosInstance.get as jest.Mock;
const mockPost = axiosInstance.post as jest.Mock;
const mockPut = axiosInstance.put as jest.Mock;

type Equal<A, B> =
  (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2
    ? true
    : false;
type Expect<T extends true> = T;

const validMarketingPlays = [
  "happy_hour",
  "featured_dish",
  "move_item",
  "win_back",
  "combo_deal",
  "offer",
] as const satisfies readonly MarketingPlay[];

const validOfferCaptionRequest = {
  item_name: "Dinner special",
  play: "offer",
} satisfies GenerateMarketingCaptionRequest;

const emptyCaptionPlay = {
  item_name: "Dinner special",
  // @ts-expect-error Caption generation requires a concrete marketing play.
  play: "",
} satisfies GenerateMarketingCaptionRequest;

const invalidCaptionPlay = {
  item_name: "Dinner special",
  // @ts-expect-error Unknown plays must not enter the caption API contract.
  play: "flash_sale",
} satisfies GenerateMarketingCaptionRequest;

const clientOwnedCaptionFacts = {
  item_name: "Dinner special",
  play: "offer",
  // @ts-expect-error Restaurant facts are server-owned, not caption controls.
  city: "Client City",
} satisfies GenerateMarketingCaptionRequest;

describe("marketing api", () => {
  beforeEach(() => jest.clearAllMocks());

  it("keeps every play-bearing contract bounded", () => {
    const checks: [
      Expect<Equal<CampaignSuggestion["play"], MarketingPlay>>,
      Expect<Equal<CampaignSuggestion["play_key"], MarketingPlay | undefined>>,
      Expect<
        Equal<GenerateMarketingImageRequest["play"], MarketingPlay | undefined>
      >,
      Expect<Equal<GenerateMarketingCaptionRequest["play"], MarketingPlay>>,
      Expect<Equal<MarketingActivity["play"], MarketingActivityPlay>>,
      Expect<
        Equal<MarketingActivityFilters["play"], MarketingPlay | "" | undefined>
      >,
      Expect<Equal<MarketingActivitySnapshot["play"], MarketingPlay>>,
      Expect<Equal<MarketingSettings["disabled_plays"], MarketingPlay[]>>,
    ] = [true, true, true, true, true, true, true, true];

    expect(checks.every(Boolean)).toBe(true);
    expect(validMarketingPlays).toContain("offer");
    expect(validOfferCaptionRequest.play).toBe("offer");
    expect(isMarketingPlay("offer")).toBe(true);
    expect(isMarketingPlay("")).toBe(false);
    expect(isMarketingPlay("flash_sale")).toBe(false);
    void emptyCaptionPlay;
    void invalidCaptionPlay;
    void clientOwnedCaptionFacts;
  });

  it("retains the complete suggestions state response", async () => {
    const response = {
      suggestions: [
        {
          id: "1:happy_hour:",
          play: "happy_hour",
          title: "T",
          why_data: "Tuesday is quiet",
          source: "analytics",
          copy_angle: "bring guests in early",
          rank: 5,
        },
      ],
      paused: false,
      empty_reason: "",
    } as const;
    mockGet.mockResolvedValue({ data: response });
    const out = await getMarketingSuggestions("42");
    expect(mockGet).toHaveBeenCalledWith(
      "/inside/businesses/42/marketing/suggestions",
    );
    expect(out).toEqual(response);
  });

  it("retains paused and the typed empty reason", async () => {
    const response = {
      suggestions: [],
      paused: true,
      empty_reason: "paused",
    } as const;
    mockGet.mockResolvedValue({ data: response });
    expect(await getMarketingSuggestionsWithState("42")).toEqual(response);
  });

  it("posts the exact native-aspect image request and retains the response", async () => {
    const response = { url: "https://s3/x.png", credit: "Generated by AI" };
    mockPost.mockResolvedValue({ data: response });
    const request = {
      name: "Carbonara",
      description: "Silky sauce",
      ingredients: "egg, cheese, pasta",
      play: "featured_dish",
      aspect_ratio: "4:5",
      template_style: "editorial",
      visual_mood: "natural",
      safe_region: "Carbonara · Tonight",
    } as const;
    const out = await generateMarketingImage("42", request);
    expect(mockPost).toHaveBeenCalledWith(
      "/inside/businesses/42/marketing/image",
      request,
    );
    expect(out).toEqual(response);
  });

  it("maps image_daily_limit_reached to a typed error with limit fields", async () => {
    mockPost.mockRejectedValue({
      response: {
        status: 429,
        data: {
          code: "image_daily_limit_reached",
          daily_limit: 500,
          resets_in_seconds: 21600,
        },
      },
    });
    await expect(generateMarketingImage("42", { name: "X" })).rejects.toEqual(
      expect.objectContaining({
        name: "ImageDailyLimitError",
        dailyLimit: 500,
        resetsInSeconds: 21600,
      }),
    );
    await expect(
      generateMarketingImage("42", { name: "X" }),
    ).rejects.toBeInstanceOf(ImageDailyLimitError);
  });

  it("does not map a bare rate-limiter 429 to ImageDailyLimitError", async () => {
    const bare429 = {
      response: { status: 429, data: { message: "too many requests" } },
    };
    mockPost.mockRejectedValue(bare429);
    await expect(generateMarketingImage("42", { name: "X" })).rejects.toBe(
      bare429,
    );
  });

  it("maps 422 prompt_rejected to a typed error", async () => {
    mockPost.mockRejectedValue({
      response: { status: 422, data: { code: "prompt_rejected" } },
    });
    await expect(
      generateMarketingImage("42", { name: "X" }),
    ).rejects.toBeInstanceOf(PromptRejectedError);
  });

  it("posts the photo the operator already has for cleanup", async () => {
    mockPost.mockResolvedValue({
      data: {
        url: "https://images.payverge.io/clean.png",
        credit: "Enhanced by AI",
      },
    });
    const result = await cleanupMarketingImage(42, {
      image_url: "https://images.payverge.io/raw.png",
      name: "Milanesa",
      aspect_ratio: "4:5",
    });
    expect(mockPost).toHaveBeenCalledWith(
      "/inside/businesses/42/marketing/image/cleanup",
      {
        image_url: "https://images.payverge.io/raw.png",
        name: "Milanesa",
        aspect_ratio: "4:5",
      },
    );
    expect(result.url).toBe("https://images.payverge.io/clean.png");
  });

  it("raises ImageDailyLimitError on cleanup image_daily_limit_reached", async () => {
    mockPost.mockRejectedValue({
      response: {
        status: 429,
        data: {
          code: "image_daily_limit_reached",
          daily_limit: 500,
          resets_in_seconds: 3600,
        },
      },
    });
    await expect(
      cleanupMarketingImage(42, {
        image_url: "https://images.payverge.io/raw.png",
        name: "Milanesa",
      }),
    ).rejects.toEqual(
      expect.objectContaining({
        name: "ImageDailyLimitError",
        dailyLimit: 500,
        resetsInSeconds: 3600,
      }),
    );
  });

  it("does not map a bare rate-limiter 429 on cleanup to ImageDailyLimitError", async () => {
    const bare429 = {
      response: { status: 429, data: { message: "too many requests" } },
    };
    mockPost.mockRejectedValue(bare429);
    await expect(
      cleanupMarketingImage(42, {
        image_url: "https://images.payverge.io/raw.png",
        name: "Milanesa",
      }),
    ).rejects.toBe(bare429);
  });

  it("throws when the caption endpoint refuses an 86'd dish", async () => {
    mockPost.mockResolvedValue({
      data: { caption: "", code: "item_unavailable", ai_available: true },
    });
    await expect(
      generateMarketingCaption("86", {
        item_name: "Steak Plate",
        play: "featured_dish",
        language: "en",
      }),
    ).rejects.toMatchObject({
      name: "MarketingCaptionUnavailableError",
      message: "item_unavailable",
    });
  });

  it("posts the exact grounded caption request and returns the caption text", async () => {
    mockPost.mockResolvedValue({ data: { caption: "Hello world" } });
    const request = {
      item_name: "Carbonara",
      play: "featured_dish",
      tone: "warm",
      language: "en",
      angle: "celebrate the best-seller",
      why_data: "Top seller this month",
    } as const;
    const out = await generateMarketingCaption("42", request);
    expect(mockPost).toHaveBeenCalledWith(
      "/inside/businesses/42/marketing/caption",
      request,
    );
    expect(out).toBe("Hello world");
  });

  it("forwards destination max_chars, hashtag_behavior, and must_include (S1-Copy)", async () => {
    mockPost.mockResolvedValue({ data: { caption: "Short story" } });
    const request = {
      item_name: "Empanada",
      play: "featured_dish" as const,
      tone: "warm" as const,
      language: "es-AR",
      max_chars: 80,
      hashtag_behavior: "none" as const,
      must_include: ["PROBALO", "@cafesur"],
    };
    await generateMarketingCaption("99", request);
    expect(mockPost).toHaveBeenCalledWith(
      "/inside/businesses/99/marketing/caption",
      request,
    );
  });

  it("forwards an optional AbortSignal to caption generation", async () => {
    mockPost.mockResolvedValue({ data: { caption: "Hello world" } });
    const request = {
      item_name: "Carbonara",
      play: "featured_dish",
      tone: "warm",
      language: "fr",
    } as const;
    const controller = new AbortController();

    await generateMarketingCaption("42", request, controller.signal);

    expect(mockPost).toHaveBeenCalledWith(
      "/inside/businesses/42/marketing/caption",
      request,
      { signal: controller.signal },
    );
  });

  it.each(validMarketingPlays)(
    "posts the bounded %s play in the caption payload",
    async (play) => {
      mockPost.mockResolvedValue({ data: { caption: "Ready" } });
      const request = { item_name: "Chef special", play };

      await generateMarketingCaption("42", request);

      expect(mockPost).toHaveBeenCalledWith(
        "/inside/businesses/42/marketing/caption",
        request,
      );
    },
  );

  it("CampaignSuggestion carries gallery enrichment fields", () => {
    const s: CampaignSuggestion = {
      id: "1:offer:offer:4",
      play: "offer",
      title: "t",
      why_data: "w",
      source: "offers",
      copy_angle: "a",
      rank: 55,
      image_url: "https://cdn/x.jpg",
      image_source: "offer",
      discount_type: "percentage",
      discount_value: 20,
    };
    expect(s.image_source).toBe("offer");
    expect(s.discount_value).toBe(20);
  });

  it("accepts S2 why_factors and guest_url on suggestions (additive)", () => {
    const s: CampaignSuggestion = {
      id: "1:featured_dish:m1",
      play: "featured_dish",
      title: "Star dish",
      why_data: "legacy prose",
      why_factors: [
        { key: "photo_ready", value: "Has a photo", weight: 5 },
        { key: "margin", value: "62%" },
      ],
      ranking_version: "s2",
      source: "menu",
      copy_angle: "celebrate",
      rank: 90,
      guest_url: "https://payverge.io/b/cafe?tab=menu",
      guest_url_kind: "menu",
    };
    expect(s.why_factors).toHaveLength(2);
    expect(s.guest_url_kind).toBe("menu");
    expect(s.ranking_version).toBe("s2");
  });

  it("recordMarketingActivity mark_ready posts creative_snapshot", async () => {
    const creativeSnapshot: MarketingCreativeSnapshot = {
      caption: "Ready for review",
      image_url: "https://cdn/x.jpg",
      image_source: "menu",
      template: "editorial",
      aspect: "4:5",
      slots: { dishName: "Milanesa" },
      crop: { x: 0.5, y: 0.5, zoom: 1 },
      destination_id: "ig_feed",
    };
    mockPost.mockResolvedValue({
      data: {
        activity: {
          id: 9,
          business_id: 42,
          suggestion_id: "1:featured_dish:m1",
          play: "featured_dish",
          title: "Featured",
          status: "ready",
          creative_snapshot: creativeSnapshot,
        },
      },
    });
    const activity = await recordMarketingActivity(42, {
      action: "mark_ready",
      suggestion: {
        id: "1:featured_dish:m1",
        play: "featured_dish",
        title: "Featured",
        target_name: "Milanesa",
      },
      creative_snapshot: creativeSnapshot,
    });
    expect(mockPost).toHaveBeenCalledWith(
      "/inside/businesses/42/marketing/activity",
      {
        action: "mark_ready",
        suggestion: {
          id: "1:featured_dish:m1",
          play: "featured_dish",
          title: "Featured",
          target_name: "Milanesa",
        },
        creative_snapshot: creativeSnapshot,
      },
    );
    expect(activity.status).toBe("ready");
    expect(activity.creative_snapshot?.destination_id).toBe("ig_feed");
  });

  it("recordMarketingActivity approve is owner handoff without requiring new snapshot", async () => {
    mockPost.mockResolvedValue({
      data: {
        activity: {
          id: 9,
          business_id: 42,
          suggestion_id: "1:featured_dish:m1",
          play: "featured_dish",
          title: "Featured",
          status: "approved",
        },
      },
    });
    const activity = await recordMarketingActivity(42, {
      action: "approve",
      suggestion: {
        id: "1:featured_dish:m1",
        play: "featured_dish",
        title: "Featured",
      },
    });
    expect(mockPost).toHaveBeenCalledWith(
      "/inside/businesses/42/marketing/activity",
      {
        action: "approve",
        suggestion: {
          id: "1:featured_dish:m1",
          play: "featured_dish",
          title: "Featured",
        },
      },
    );
    expect(activity.status).toBe("approved");
  });

  it("creative snapshot accepts superiority additive fields", () => {
    const snap: MarketingCreativeSnapshot = {
      caption: "c",
      image_url: "https://cdn/x.jpg",
      image_source: "generated",
      template: "editorial",
      aspect: "4:5",
      slots: {},
      crop: { x: 0.5, y: 0.5, zoom: 1 },
      destination_id: "print_tent",
      promo_code: "PV-FD-ABCD",
      print_preset: "table_tent_5x7",
      kit: "editorial",
      composition: "badgeHero",
    };
    expect(snap.destination_id).toBe("print_tent");
    expect(snap.promo_code).toMatch(/^PV-/);
    expect(snap.print_preset).toBe("table_tent_5x7");
  });

  it("getMarketingActivity retains nullable creative snapshots and exact page state", async () => {
    const response = {
      activity: [
        {
          id: 1,
          business_id: 42,
          suggestion_id: "1:offer:o1",
          play: "offer",
          title: "Dinner offer",
          target_name: "Carbonara",
          status: "posted",
          image_url: "https://cdn/legacy.jpg",
          caption: "Legacy caption",
          creative_snapshot: null,
          posted_at: "2026-07-14T12:00:00Z",
          created_by: "staff:7",
          created_at: "2026-07-14T12:00:00Z",
          updated_at: "2026-07-14T12:00:00Z",
        },
      ],
      total: 1,
      page: 1,
      per_page: 20,
    };
    mockGet.mockResolvedValue({ data: response });
    const page = await getMarketingActivity(42, {
      status: "posted",
      handled_from: "2026-06-15T12:00:00Z",
      page: 1,
      per_page: 20,
    });
    expect(mockGet).toHaveBeenCalledWith(
      "/inside/businesses/42/marketing/activity",
      {
        params: {
          status: "posted",
          handled_from: "2026-06-15T12:00:00Z",
          page: 1,
          per_page: 20,
        },
      },
    );
    expect(page).toEqual(response);
    expect(page.activity[0].creative_snapshot).toBeNull();
  });

  it("normalizes unknown activity plays to a bounded sentinel", async () => {
    const activity = {
      id: 2,
      business_id: 42,
      suggestion_id: "1:seasonal_push:x",
      play: "seasonal_push",
      title: "Legacy campaign",
      target_name: "Soup",
      status: "posted",
      image_url: "",
      caption: "",
      creative_snapshot: null,
      created_by: "staff:7",
      created_at: "2026-07-14T12:00:00Z",
      updated_at: "2026-07-14T12:00:00Z",
    };
    mockGet.mockResolvedValue({
      data: { activity: [activity], total: 1, page: 1, per_page: 20 },
    });

    const page = await getMarketingActivity(42);

    expect(page.activity[0]).toEqual({
      ...activity,
      play: "unknown",
      raw_play: "seasonal_push",
    });
  });

  it("recordMarketingActivity posts and returns the exact approved creative snapshot", async () => {
    const creativeSnapshot: MarketingCreativeSnapshot = {
      caption: "Tonight's carbonara",
      image_url: "https://cdn/carbonara.jpg",
      image_source: "generated",
      template: "editorial",
      aspect: "4:5",
      slots: { dishName: "Carbonara", cta: "Book tonight" },
      crop: { x: 0.42, y: 0.31, zoom: 1.35 },
      font_family: "Serif",
    };
    const request = {
      action: "post" as const,
      suggestion: {
        id: "1:offer:o1",
        play: "offer" as const,
        title: "Dinner offer",
        target_name: "Carbonara",
        image_url: creativeSnapshot.image_url,
        caption: creativeSnapshot.caption,
      },
      creative_snapshot: creativeSnapshot,
    };
    const activity = {
      id: 1,
      business_id: 42,
      suggestion_id: request.suggestion.id,
      play: "offer",
      title: "Dinner offer",
      target_name: "Carbonara",
      status: "posted" as const,
      image_url: creativeSnapshot.image_url,
      caption: creativeSnapshot.caption,
      creative_snapshot: creativeSnapshot,
      posted_at: "2026-07-14T12:00:00Z",
      created_by: "staff:7",
      created_at: "2026-07-14T12:00:00Z",
      updated_at: "2026-07-14T12:00:00Z",
    };
    mockPost.mockResolvedValue({ data: { activity } });
    const out = await recordMarketingActivity(42, request);
    expect(mockPost).toHaveBeenCalledWith(
      "/inside/businesses/42/marketing/activity",
      request,
    );
    expect(out).toEqual(activity);
  });

  it("keeps creative font families bounded to renderer-supported values", () => {
    const invalid: MarketingCreativeSnapshot = {
      caption: "Caption",
      image_url: "https://cdn/c.jpg",
      image_source: "menu",
      template: "editorial",
      aspect: "4:5",
      slots: {},
      crop: { x: 0.5, y: 0.5, zoom: 1 },
      // @ts-expect-error Unsupported fonts must not enter the snapshot contract.
      font_family: "Papyrus",
    };
    expect(invalid.font_family).toBe("Papyrus");
  });

  it("carries an art-direction choice on the snapshot, and still accepts one saved before kits existed", () => {
    const base = {
      caption: "Chalked up",
      image_url: "https://cdn/board.jpg",
      image_source: "generated" as const,
      template: "editorial" as const,
      aspect: "4:5" as const,
      slots: { dishName: "Carbonara" },
      crop: { x: 0.5, y: 0.5, zoom: 1 },
    };
    const scene: MarketingCreativeSnapshot = {
      ...base,
      kit: "chalkboard",
      composition: "posterStack",
      treatment: "duotone",
    };
    expect(scene.kit).toBe("chalkboard");
    expect(scene.composition).toBe("posterStack");
    expect(scene.treatment).toBe("duotone");

    // Deliberately unconstrained on the wire: a backend older or newer than
    // this build may send an id this build has no definition for, and the
    // consumer — not the type — is what has to fall back safely.
    const unknownToThisBuild: MarketingCreativeSnapshot = {
      ...base,
      kit: "neon-vaporwave",
    };
    expect(unknownToThisBuild.kit).toBe("neon-vaporwave");

    // Every snapshot written before Wave 1 omits all three.
    const legacy: MarketingCreativeSnapshot = { ...base };
    expect(legacy.kit).toBeUndefined();
    expect(legacy.composition).toBeUndefined();
    expect(legacy.treatment).toBeUndefined();
  });

  it("restoreMarketingActivity posts a restore action and returns restored flag", async () => {
    mockPost.mockResolvedValue({ data: { restored: true } });
    const res = await restoreMarketingActivity(42, "1:offer:o1");
    expect(mockPost).toHaveBeenCalledWith(
      "/inside/businesses/42/marketing/activity",
      { action: "restore", suggestion_id: "1:offer:o1" },
    );
    expect(res).toBe(true);
  });

  it("getMarketingSettings retains the complete creative profile", async () => {
    const creativeProfile: MarketingCreativeProfile = {
      audience: "neighborhood regulars",
      voice: "warm and specific",
      visual_mood: "editorial",
      cta_style: "direct",
      hashtag_behavior: "light",
      avoid_phrases: ["best ever"],
      default_language: "es-AR",
      default_tone: "punchy",
    };
    const response = {
      enabled: false,
      disabled_plays: ["offer" as const],
      creative_profile: creativeProfile,
    };
    mockGet.mockResolvedValue({ data: response });
    const s = await getMarketingSettings(42);
    expect(s).toEqual(response);
  });

  it("updateMarketingSettings puts and retains every settings field", async () => {
    const settings = {
      enabled: true,
      disabled_plays: [],
      creative_profile: {
        audience: "local diners",
        voice: "clear",
        visual_mood: "bright" as const,
        cta_style: "soft" as const,
        hashtag_behavior: "standard" as const,
        avoid_phrases: [],
        default_language: "en",
        default_tone: "warm" as const,
      },
    };
    mockPut.mockResolvedValue({ data: settings });
    const s = await updateMarketingSettings(42, settings);
    expect(mockPut).toHaveBeenCalledWith(
      "/inside/businesses/42/marketing/settings",
      settings,
    );
    expect(s).toEqual(settings);
  });

});
