#!/usr/bin/env bash
# Stage the files attached to a GitHub release.
#
#   scripts/ci/release-assets.sh <version> <out-dir>
#
# <version> is the release version without the leading "v" (1.2.3 or
# 1.2.3-rc.1). <out-dir> must not exist yet. The script writes:
#
#   install.sh                       deploy/install.sh
#   docker-compose.yml               deploy/docker-compose.yml
#   Caddyfile                        deploy/Caddyfile
#   env.example                      deploy/.env.example. GitHub renames asset
#                                    names with a leading dot, so the dot is
#                                    dropped here and the name stays predictable.
#   payverge-deploy-<version>.tar.gz every tracked file under deploy/ at HEAD,
#                                    including the Caddy snippets the compose
#                                    file mounts, plus the repository's
#                                    LICENSE and NOTICE, in
#                                    payverge-deploy-<version>/
#   THIRD_PARTY_LICENSES.md          regenerated by
#                                    scripts/licenses/generate-third-party.sh
#   SHA256SUMS                       sha256 of every file above
#
# Run from a clean checkout of the release tag. Needs git 2.35 or later
# (git archive --add-file). The licence generator needs Go, go-licenses
# (installed on demand) and an installed frontend/node_modules.
# RELEASE_ASSETS_ROOT overrides the repository root (tests only).
set -euo pipefail

usage() {
  echo "usage: $0 <version> <out-dir>" >&2
  exit 2
}

[[ $# -eq 2 ]] || usage
version="$1"
out="$2"

if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$ ]]; then
  echo "release-assets: version must be X.Y.Z or X.Y.Z-pre without a leading v, got '$version'" >&2
  exit 2
fi
if [[ -e "$out" ]]; then
  echo "release-assets: $out already exists; pass a fresh directory" >&2
  exit 2
fi

root="${RELEASE_ASSETS_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
cd "$root"

# deploy/ source -> release asset name.
assets=(
  "deploy/install.sh:install.sh"
  "deploy/docker-compose.yml:docker-compose.yml"
  "deploy/Caddyfile:Caddyfile"
  "deploy/.env.example:env.example"
)
# Repository files at the root of the deploy tarball, next to deploy/'s files.
legal=(LICENSE NOTICE)

missing=0
for src in "${assets[@]%%:*}" "${legal[@]}"; do
  if ! git ls-files --error-unmatch -- "$src" >/dev/null 2>&1; then
    echo "release-assets: $src is not a tracked file" >&2
    missing=1
  fi
done
[[ $missing -eq 0 ]] || exit 1

mkdir -p "$out"
out="$(cd "$out" && pwd)"

# Copy from HEAD, not the working tree, so a stray local edit can never ship.
for pair in "${assets[@]}"; do
  src="${pair%%:*}"
  dst="${pair##*:}"
  git show "HEAD:$src" >"$out/$dst"
done
chmod 0755 "$out/install.sh"

legal_dir="$(mktemp -d)"
trap 'rm -rf "$legal_dir"' EXIT
add_files=()
for f in "${legal[@]}"; do
  git show "HEAD:$f" >"$legal_dir/$f"
  add_files+=("--add-file=$legal_dir/$f")
done
# --add-file puts each file under the --prefix given before it.
git archive --format=tar.gz --prefix="payverge-deploy-$version/" "${add_files[@]}" \
  -o "$out/payverge-deploy-$version.tar.gz" HEAD:deploy

bash scripts/licenses/generate-third-party.sh
licenses="docs/licensing/THIRD_PARTY_LICENSES.md"
if [[ ! -s "$licenses" ]]; then
  echo "release-assets: the licence generator did not write $licenses" >&2
  exit 1
fi
cp "$licenses" "$out/THIRD_PARTY_LICENSES.md"

if command -v sha256sum >/dev/null 2>&1; then
  sha=(sha256sum)
else
  sha=(shasum -a 256)
fi
(
  cd "$out"
  # Sorted, file names only: the sums file is reproducible. The list is taken
  # before SHA256SUMS exists, so it never hashes itself.
  mapfile -t files < <(find . -maxdepth 1 -type f -exec basename {} \; | LC_ALL=C sort)
  for f in "${files[@]}"; do "${sha[@]}" "$f"; done >SHA256SUMS
)

echo "release-assets: staged $(find "$out" -maxdepth 1 -type f | wc -l | tr -d ' ') files for $version in $out"
