#!/usr/bin/env bash
# Payverge installer: one self-hosted instance with Docker Compose.
#
#   curl -fsSL https://github.com/stdevMac/payverge/releases/latest/download/install.sh -o install.sh
#   less install.sh        # read it first
#   bash install.sh
#
# or, from a clone of the repository:
#
#   ./deploy/install.sh    # installs in place, in deploy/
#
# What it does:
#   1. checks Docker Engine and the Compose v2 plugin;
#   2. fetches the deploy files of a release (checksum-verified, and
#      signature-verified when cosign is available) into the install
#      directory, or uses the checkout it runs from;
#   3. asks for the domain, the admin email and demo data (or takes flags);
#   4. writes .env (mode 600) with freshly generated secrets. An existing .env
#      is never overwritten unless you pass --force. A clone never records
#      PAYVERGE_VERSION=latest: a release number, or "local" when building;
#   5. runs `docker compose up -d`, waits for /api/v1/health/ready, probes
#      the public backend and frontend through Caddy, and prints the URL and
#      the generated admin password, once. A failed probe exits non-zero
#      after that summary.
#
# Re-running it is safe: it keeps .env, upgrades the files when you pass
# --version, and starts whatever is not running. Before an upgrade of an
# existing database it takes a backup set (skip with --no-backup). Nothing is
# sent anywhere except the GitHub release download and the image pulls.
#
# Every flag has an environment variable (PAYVERGE_DOMAIN, ...) for
# unattended installs. Run with --help for the list.
set -Eeuo pipefail

readonly REPO="stdevMac/payverge"
# PAYVERGE_RELEASES_URL: a mirror laid out like GitHub releases (download/vX.Y.Z/...).
readonly RELEASES_URL=${PAYVERGE_RELEASES_URL:-https://github.com/${REPO}/releases}
# Keyless identity of the workflow that signs SHA256SUMS (cosign sign-blob --bundle).
readonly RELEASE_SIGNER=https://github.com/stdevMac/payverge/.github/workflows/release.yml@refs/heads/main
readonly MIN_COMPOSE="2.20.0"
readonly READY_TIMEOUT=${PAYVERGE_READY_TIMEOUT:-600}
# Tries, 5 seconds apart, of the public backend and frontend check.
readonly PROBE_ATTEMPTS=${PAYVERGE_PROBE_ATTEMPTS:-24}
# Seconds before a docker call that should answer at once counts as hung.
readonly DOCKER_TIMEOUT=${PAYVERGE_DOCKER_TIMEOUT:-30}
readonly GENERATED_MARK="# ADMIN_PASSWORD was generated by install.sh and is removed after the first start."
# die() exits with this status; the ERR trap stays quiet for it because die
# already said what went wrong.
readonly DIE_STATUS=3

# Files a release (or a checkout) provides. .env, backups/ and rclone/ are the
# operator's and are never touched by an upgrade.
readonly DEPLOY_FILES="docker-compose.yml docker-compose.build.yml Caddyfile Caddyfile.cloudflare payverge.caddy cloudflare-cidrs.caddy .env.example README.md install.sh backup/backup.sh backup/restore.sh postgres/init-app-role.sql monitoring/alerts.yml monitoring/alerts.test.yml"

domain=${PAYVERGE_DOMAIN:-}
admin_email=${PAYVERGE_ADMIN_EMAIL:-}
acme_email=${PAYVERGE_ACME_EMAIL:-}
demo=${PAYVERGE_DEMO:-}
install_dir=${PAYVERGE_DIR:-}
version=${PAYVERGE_INSTALL_VERSION:-}
http_port=${PAYVERGE_HTTP_PORT:-}
https_port=${PAYVERGE_HTTPS_PORT:-}
assume_yes=${PAYVERGE_YES:-0}
dry_run=${PAYVERGE_DRY_RUN:-0}
force=${PAYVERGE_FORCE:-0}
build=${PAYVERGE_BUILD:-0}
no_backup=${PAYVERGE_NO_BACKUP:-0}
require_signature=${PAYVERGE_REQUIRE_SIGNATURE:-0}
start=1
# probe_https records a public check that failed; main warns and exits after
# the summary, so the generated admin password is still printed once.
probe_failed=0
probe_backend_failed=0
probe_frontend_failed=0
probe_scheme=""
probe_bind=""
probe_port=""
version_requested=0
[[ -z $version ]] || version_requested=1

# --- output ------------------------------------------------------------------

if [[ -t 1 ]]; then
	bold=$'\033[1m' dim=$'\033[2m' red=$'\033[31m' yellow=$'\033[33m' green=$'\033[32m' reset=$'\033[0m'
else
	bold="" dim="" red="" yellow="" green="" reset=""
fi

say() { printf '%s\n' "$*"; }
step() { printf '%s==>%s %s\n' "$bold" "$reset" "$*"; }
note() { printf '    %s\n' "$*"; }
warn() { printf '%swarning:%s %s\n' "$yellow" "$reset" "$*" >&2; }
die() {
	printf '%serror:%s %s\n' "$red" "$reset" "$*" >&2
	exit "$DIE_STATUS"
}

# Any other failing command would end the script under `set -e` without a
# word; name it instead. Subshells leave the report to the top level.
on_error() {
	local status=$1 line=$2 command=$3
	((BASH_SUBSHELL == 0)) || return 0
	((status != DIE_STATUS)) || return 0
	[[ $command != '"$@"' ]] || command=$last_run
	# shellcheck disable=SC2016 # the backticks are shown to the operator; they are not expansion
	printf '%serror:%s install.sh stopped at line %s: `%s` failed (exit %s). Nothing after that step ran; fix the cause and run install.sh again.\n' \
		"$red" "$reset" "$line" "$command" "$status" >&2
}
trap 'on_error $? $LINENO "$BASH_COMMAND"' ERR

# run CMD...: execute, or only print it under --dry-run. Never pass a secret
# as an argument to run: it would be printed.
last_run=""
run() {
	if [[ $dry_run == 1 ]]; then
		printf '%s[dry-run]%s %s\n' "$dim" "$reset" "$*"
		return 0
	fi
	last_run="$*"
	"$@"
}

usage() {
	cat <<'EOF'
Usage: install.sh [options]

  --domain NAME        public host name (DNS must point here), or localhost
                       for a local trial                    [PAYVERGE_DOMAIN]
  --admin-email EMAIL  first platform admin                 [PAYVERGE_ADMIN_EMAIL]
  --acme-email EMAIL   Let's Encrypt account email (optional) [PAYVERGE_ACME_EMAIL]
  --demo / --no-demo   seed demo restaurants on first boot   [PAYVERGE_DEMO=1|0]
  --dir DIR            install directory (default: /opt/payverge as root,
                       ~/payverge otherwise; in place when run from a
                       checkout)                             [PAYVERGE_DIR]
  --version V          release to install or upgrade to: 1.2.3, v1.2.3 or
                       latest (default: latest)    [PAYVERGE_INSTALL_VERSION]
  --http-port [ADDR:]N host port for HTTP (default 80; 127.0.0.1:80 for a
                       localhost trial)                      [PAYVERGE_HTTP_PORT]
  --https-port [ADDR:]N
                       host port for HTTPS (default 443; 127.0.0.1:443 for a
                       localhost trial)                     [PAYVERGE_HTTPS_PORT]
  -y, --yes            no prompts; fail if a required value is missing
                                                             [PAYVERGE_YES=1]
  --dry-run            print what would happen, change nothing [PAYVERGE_DRY_RUN=1]
  --force              rewrite an existing .env (a copy is kept; the database,
                       JWT and plugin secrets are carried over) [PAYVERGE_FORCE=1]
  --build              build the images from this checkout instead of pulling
                       them (run from a clone, in place)     [PAYVERGE_BUILD=1]
  --no-backup          upgrade without taking a backup set first
                                                       [PAYVERGE_NO_BACKUP=1]
  --require-signature  verify SHA256SUMS with cosign; refuse to install if
                       cosign is missing or the signature fails
                                           [PAYVERGE_REQUIRE_SIGNATURE=1]
  --no-start           write the files and .env, do not start the stack
  -h, --help           this help
EOF
}

need_value() {
	[[ $# -ge 2 && -n $2 && $2 != -* ]] || die "$1 needs a value (see --help)"
}

while [[ $# -gt 0 ]]; do
	case $1 in
	--domain) need_value "$@" && domain=$2 && shift ;;
	--domain=*) domain=${1#*=} ;;
	--admin-email) need_value "$@" && admin_email=$2 && shift ;;
	--admin-email=*) admin_email=${1#*=} ;;
	--acme-email) need_value "$@" && acme_email=$2 && shift ;;
	--acme-email=*) acme_email=${1#*=} ;;
	--demo) demo=1 ;;
	--no-demo) demo=0 ;;
	--dir) need_value "$@" && install_dir=$2 && shift ;;
	--dir=*) install_dir=${1#*=} ;;
	--version) need_value "$@" && version=$2 && version_requested=1 && shift ;;
	--version=*) version=${1#*=} && version_requested=1 ;;
	--http-port) need_value "$@" && http_port=$2 && shift ;;
	--http-port=*) http_port=${1#*=} ;;
	--https-port) need_value "$@" && https_port=$2 && shift ;;
	--https-port=*) https_port=${1#*=} ;;
	-y | --yes) assume_yes=1 ;;
	--dry-run) dry_run=1 ;;
	--force) force=1 ;;
	--build) build=1 ;;
	--no-backup) no_backup=1 ;;
	--require-signature) require_signature=1 ;;
	--no-start) start=0 ;;
	-h | --help)
		usage
		exit 0
		;;
	*) die "unknown option: $1 (see --help)" ;;
	esac
	shift
done

# --- helpers -----------------------------------------------------------------

lower() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]'; }

is_true() {
	case $(lower "${1:-}") in
	1 | y | yes | true | on) return 0 ;;
	*) return 1 ;;
	esac
}

have() { command -v "$1" >/dev/null 2>&1; }

interactive() {
	[[ $assume_yes != 1 ]] && [[ -r /dev/tty ]] && { : </dev/tty; } 2>/dev/null
}

# ask VAR PROMPT [DEFAULT]: read one line from the terminal (works under
# curl | bash, where stdin is the script).
ask() {
	local __var=$1 __prompt=$2 __default=${3:-} __reply=""
	if [[ -n $__default ]]; then
		__prompt="$__prompt [$__default]"
	fi
	printf '%s: ' "$__prompt" >/dev/tty
	IFS= read -r __reply </dev/tty || true
	[[ -n $__reply ]] || __reply=$__default
	printf -v "$__var" '%s' "$__reply"
}

valid_domain() {
	local d=$1
	[[ ${#d} -le 253 ]] || return 1
	[[ $d =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}$ ]] && return 0
	[[ $d =~ ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)*$ ]]
}

# normalize_domain: lower-case DOMAIN and strip a scheme or path pasted with it.
normalize_domain() {
	domain=$(lower "$domain")
	domain=${domain#http://}
	domain=${domain#https://}
	domain=${domain%%/*}
	valid_domain "$domain" || die "'$domain' is not a valid host name"
}

valid_email() {
	[[ $1 =~ ^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$ || $1 =~ ^[^[:space:]@]+@localhost$ ]]
}

valid_port() {
	[[ $1 =~ ^[0-9]+$ ]] && ((10#$1 >= 1 && 10#$1 <= 65535))
}

# valid_port_spec VALUE: PORT, IPV4:PORT or [IPV6]:PORT (what compose accepts
# on the host side of a port mapping).
valid_port_spec() {
	local v=$1
	if [[ $v == *:* ]]; then
		local addr=${v%:*}
		[[ $addr =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}$ || $addr =~ ^\[[0-9A-Fa-f:.]+\]$ ]] || return 1
		v=${v##*:}
	fi
	valid_port "$v"
}

# loopback_name NAME: a trial name that only this machine can reach, so the
# stack is published on 127.0.0.1 instead of every interface.
loopback_name() {
	case $1 in
	localhost | *.localhost | 127.*) return 0 ;;
	*) return 1 ;;
	esac
}

# bind_loopback: localhost trial ports default to 127.0.0.1 (an explicit
# ADDR:PORT, such as 0.0.0.0:8443, is kept).
bind_loopback() {
	[[ $http_port == *:* ]] || http_port=127.0.0.1:${http_port:-80}
	[[ $https_port == *:* ]] || https_port=127.0.0.1:${https_port:-443}
}

# valid_project_name NAME: what docker compose accepts for a project name.
valid_project_name() {
	[[ $1 =~ ^[a-z0-9][a-z0-9_-]*$ ]]
}

# Served with a certificate from Caddy's own CA instead of a public one.
# valid_proxy_cidrs VALUE: TRUSTED_PROXY_CIDRS is a space-separated list of
# IPv4/IPv6 addresses or CIDRs (or Caddy's private_ranges). Caddy splices it
# into its global options, so anything else would break or widen the config.
# Ranges broader than /8 (IPv4) or /16 (IPv6) are refused: a /0, or a pair of
# /1 halves, would trust every client's X-Forwarded-For.
valid_proxy_cidrs() {
	local token ip prefix
	set -f
	# shellcheck disable=SC2086 # word splitting on spaces is the format
	set -- $1
	set +f
	(($# > 0)) || return 1
	for token in "$@"; do
		[[ $token != private_ranges ]] || continue
		ip=${token%%/*}
		prefix=
		[[ $token != */* ]] || prefix=${token#*/}
		if [[ $ip =~ ^([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$ ]]; then
			((BASH_REMATCH[1] <= 255 && BASH_REMATCH[2] <= 255 && BASH_REMATCH[3] <= 255 && BASH_REMATCH[4] <= 255)) || return 1
			[[ -z $prefix ]] || { [[ $prefix =~ ^[0-9]{1,2}$ ]] && ((10#$prefix >= 8 && 10#$prefix <= 32)); } || return 1
		elif [[ $ip =~ ^[0-9A-Fa-f:.]+$ && $ip == *:*:* ]]; then
			[[ -z $prefix ]] || { [[ $prefix =~ ^[0-9]{1,3}$ ]] && ((10#$prefix >= 16 && 10#$prefix <= 128)); } || return 1
		else
			return 1
		fi
	done
}

internal_tls_name() {
	local d=$1
	[[ $d =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}$ ]] && return 0
	case $d in
	localhost | *.localhost | *.local | *.internal | *.home.arpa) return 0 ;;
	*) return 1 ;;
	esac
}

version_ge() { # version_ge A B: A >= B (dotted numeric)
	local a b i
	IFS=. read -r -a a <<<"$1"
	IFS=. read -r -a b <<<"$2"
	for i in 0 1 2; do
		((10#${a[i]:-0} > 10#${b[i]:-0})) && return 0
		((10#${a[i]:-0} < 10#${b[i]:-0})) && return 1
	done
	return 0
}

# env_get KEY FILE: last value of KEY in a dotenv file, quotes removed.
env_get() {
	local key=$1 file=$2 line value=""
	[[ -f $file ]] || return 0
	while IFS= read -r line || [[ -n $line ]]; do
		case $line in
		"$key="*) value=${line#*=} ;;
		esac
	done <"$file"
	value=${value%$'\r'}
	if [[ $value == \'*\' || $value == \"*\" ]]; then
		value=${value:1:${#value}-2}
	fi
	printf '%s' "$value"
}

env_has() { # env_has KEY FILE: KEY is set (possibly empty) in FILE
	[[ -f $2 ]] && grep -q "^$1=" "$2"
}

# --- randomness --------------------------------------------------------------

rand_hex() { # rand_hex BYTES
	if have openssl; then
		openssl rand -hex "$1"
	else
		od -An -N"$1" -tx1 /dev/urandom | tr -d ' \n'
	fi
}

rand_b64() { # rand_b64 BYTES
	if have openssl; then
		openssl rand -base64 "$1" | tr -d '\n'
	else
		head -c "$1" /dev/urandom | base64 | tr -d '\n'
	fi
}

random_bytes() { # random_bytes N: N decimal byte values, one per line
	if have openssl; then
		openssl rand "$1" | od -An -v -tu1
	else
		od -An -v -N"$1" -tu1 /dev/urandom
	fi | tr -s ' ' '\n' | sed '/^$/d'
}

# 4 groups of 5 from an alphabet without look-alikes (0/O, 1/l/I):
# about 116 bits, easy to type, and it meets the admin password policy.
gen_admin_password() {
	local alphabet="abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789"
	local n=${#alphabet} limit chars="" byte distinct
	limit=$((256 - 256 % n))
	while :; do
		chars=""
		while [[ ${#chars} -lt 20 ]]; do
			while IFS= read -r byte; do
				((byte < limit)) || continue
				chars+=${alphabet:byte%n:1}
				[[ ${#chars} -lt 20 ]] || break
			done < <(random_bytes 64)
		done
		distinct=$(printf '%s' "$chars" | fold -w1 | sort -u | wc -l | tr -d ' ')
		((distinct >= 8)) && break
	done
	printf '%s-%s-%s-%s' "${chars:0:5}" "${chars:5:5}" "${chars:10:5}" "${chars:15:5}"
}

# --- docker ------------------------------------------------------------------

compose() {
	(cd "$install_dir" && docker compose "$@")
}

# with_timeout SECONDS CMD...: run CMD, killing it after SECONDS (a wedged
# daemon makes every docker call hang). Uses timeout(1) when present, else a
# watchdog, so it also works on a stock macOS.
with_timeout() {
	local secs=$1 pid watcher status=0
	shift
	if have timeout; then
		timeout "$secs" "$@"
		return
	fi
	"$@" &
	pid=$!
	(
		sleep "$secs"
		kill -TERM "$pid" 2>/dev/null
	) >/dev/null 2>&1 </dev/null &
	watcher=$!
	wait "$pid" || status=$?
	kill "$watcher" 2>/dev/null || true
	wait "$watcher" 2>/dev/null || true
	return "$status"
}

# docker_answers: the daemon replies within DOCKER_TIMEOUT seconds.
docker_answers() {
	with_timeout "$DOCKER_TIMEOUT" docker info >/dev/null 2>&1
}

docker_up=0
check_docker() {
	step "Checking Docker"
	if ! have docker; then
		[[ $dry_run == 1 ]] && {
			warn "docker not found (install Docker Engine: https://docs.docker.com/engine/install/)"
			return 0
		}
		die "docker not found. Install Docker Engine and the Compose plugin: https://docs.docker.com/engine/install/"
	fi
	local cv
	if ! cv=$(with_timeout "$DOCKER_TIMEOUT" docker compose version --short 2>/dev/null); then
		[[ $dry_run == 1 ]] && {
			warn "the Docker Compose v2 plugin is missing"
			return 0
		}
		die "the Docker Compose v2 plugin is missing ('docker compose', not 'docker-compose'). Install docker-compose-plugin: https://docs.docker.com/compose/install/linux/"
	fi
	cv=${cv#v}
	if ! version_ge "$cv" "$MIN_COMPOSE"; then
		die "Docker Compose $cv is too old; $MIN_COMPOSE or newer is required"
	fi
	if ! docker_answers; then
		local hint="start (or restart) the Docker daemon"
		if [[ $(id -u) -ne 0 ]]; then
			hint="start the Docker daemon, or run as root / add $(id -un) to the docker group"
		fi
		[[ $dry_run == 1 ]] && {
			warn "cannot talk to the Docker daemon: $hint"
			return 0
		}
		die "cannot talk to the Docker daemon: $hint"
	fi
	docker_up=1
	note "Docker $(with_timeout "$DOCKER_TIMEOUT" docker version --format '{{.Server.Version}}' 2>/dev/null || echo '?'), Compose $cv"
}

# Name of the compose project in install_dir (the `name:` key unless
# COMPOSE_PROJECT_NAME overrides it).
project_name() {
	local name=${COMPOSE_PROJECT_NAME:-}
	if [[ -z $name && -f $install_dir/.env ]]; then
		name=$(env_get COMPOSE_PROJECT_NAME "$install_dir/.env")
	fi
	if [[ -z $name && -f $install_dir/docker-compose.yml ]]; then
		name=$(sed -n 's/^name:[[:space:]]*\([A-Za-z0-9_-]*\).*/\1/p' "$install_dir/docker-compose.yml" | head -n 1)
	fi
	printf '%s' "${name:-payverge}"
}

db_volume_exists() {
	[[ $docker_up == 1 ]] || return 1
	[[ -n $(docker volume ls -q --filter "label=com.docker.compose.project=$(project_name)" --filter "label=com.docker.compose.volume=db" 2>/dev/null) ]]
}

# --- sources -----------------------------------------------------------------

script_dir=""
if [[ -n ${BASH_SOURCE[0]:-} && -f ${BASH_SOURCE[0]} ]]; then
	script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
fi
# local_source: deploy/ of a clone (backend/ next to it); files are copied
# from it, or used in place. installed_dir: an earlier install; re-running its
# install.sh upgrades it from the release.
local_source=""
installed_dir=""
if [[ -n $script_dir && -f $script_dir/docker-compose.yml && -f $script_dir/payverge.caddy ]]; then
	if [[ -f $script_dir/../backend/Dockerfile ]]; then
		local_source=$script_dir
	else
		installed_dir=$script_dir
	fi
fi

normalize_version() {
	case $version in
	"" | latest) version=latest ;;
	v[0-9]*) version=${version#v} ;;
	esac
	[[ $version == latest || $version =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$ ]] ||
		die "--version must be latest, 1.2.3 or v1.2.3 (got '$version')"
}

resolve_latest() {
	local url
	have curl || die "curl is required to download the release"
	url=$(curl -fsSLI -o /dev/null -w '%{url_effective}' "$RELEASES_URL/latest") ||
		die "could not reach $RELEASES_URL"
	case $url in
	*/releases/tag/v*) printf '%s' "${url##*/tag/v}" ;;
	*) die "no published release found at $RELEASES_URL; clone the repository and run deploy/install.sh instead" ;;
	esac
}

sha256_check() { # sha256_check SUMFILE (in the current directory)
	if have sha256sum; then
		sha256sum -c --status "$1"
	elif have shasum; then
		shasum -a 256 -c -s "$1"
	else
		die "need sha256sum or shasum to verify the download"
	fi
}

# verify_release_signature BASE: trust SHA256SUMS in the current directory
# only after its keyless cosign bundle checks out. Dry-run prints the
# download and the cosign command. Cosign missing is a note here; the hard
# stop for --require-signature happens before any download.
verify_release_signature() {
	local base=$1
	if ! have cosign; then
		note "only the checksum is checked; install cosign (https://docs.sigstore.dev/cosign/system_config/installation/) and re-run with --require-signature to verify the signature of SHA256SUMS"
		return 0
	fi
	if [[ $dry_run == 1 ]]; then
		run curl -fsSLO "$base/SHA256SUMS.sigstore.json"
		run cosign verify-blob --bundle SHA256SUMS.sigstore.json \
			--certificate-identity "$RELEASE_SIGNER" \
			--certificate-oidc-issuer https://token.actions.githubusercontent.com \
			SHA256SUMS
		return 0
	fi
	curl -fsSL --proto '=https' --tlsv1.2 -o SHA256SUMS.sigstore.json "$base/SHA256SUMS.sigstore.json" ||
		die "download failed: $base/SHA256SUMS.sigstore.json"
	cosign verify-blob --bundle SHA256SUMS.sigstore.json \
		--certificate-identity "$RELEASE_SIGNER" \
		--certificate-oidc-issuer https://token.actions.githubusercontent.com \
		SHA256SUMS ||
		die "signature check failed for SHA256SUMS; not installing it"
	note "signature verified (cosign)"
}

fetch_release() { # fetch_release VERSION
	local v=$1 tmp tarball="payverge-deploy-$1.tar.gz" base="$RELEASES_URL/download/v$1"
	if [[ $require_signature == 1 ]] && ! have cosign; then
		die "cosign is required to verify the release signature; install it (https://docs.sigstore.dev/cosign/system_config/installation/) or drop --require-signature"
	fi
	step "Downloading release v$v"
	if [[ $dry_run == 1 ]]; then
		run curl -fsSLO "$base/$tarball"
		run curl -fsSLO "$base/SHA256SUMS"
		verify_release_signature "$base"
		run sha256sum -c "(the $tarball line of SHA256SUMS)"
		run tar -xzf "$tarball" --strip-components=1 -C "$install_dir"
		return 0
	fi
	tmp=$(mktemp -d)
	# shellcheck disable=SC2064 # expand tmp now
	trap "rm -rf '$tmp'" EXIT
	(
		cd "$tmp"
		curl -fsSL --proto '=https' --tlsv1.2 -o "$tarball" "$base/$tarball" ||
			die "download failed: $base/$tarball"
		curl -fsSL --proto '=https' --tlsv1.2 -o SHA256SUMS "$base/SHA256SUMS" ||
			die "download failed: $base/SHA256SUMS"
		verify_release_signature "$base"
		awk -v f="$tarball" '$2 == f || $2 == "*" f' SHA256SUMS >one.sum
		[[ -s one.sum ]] || die "SHA256SUMS has no entry for $tarball"
		sha256_check one.sum || die "checksum mismatch for $tarball; not installing it"
		mkdir stage
		tar -xzf "$tarball" --strip-components=1 -C stage
	)
	note "checksum verified"
	mkdir -p "$install_dir"
	install_tree "$tmp/stage" "$install_dir"
	rm -rf "$tmp"
	trap - EXIT
}

# install_tree SRC DEST: copy every file of SRC into DEST. Each file is
# renamed into place, so the install.sh running right now keeps reading its
# old copy. .env, backups/ and rclone/ are not in a release and stay as they are.
install_tree() {
	local src=$1 dest=$2 f
	while IFS= read -r f; do
		f=${f#./}
		mkdir -p "$dest/$(dirname "$f")"
		cp -p "$src/$f" "$dest/$f.new.$$"
		mv -f "$dest/$f.new.$$" "$dest/$f"
	done < <(cd "$src" && find . -type f)
}

copy_checkout() {
	local f
	step "Copying the deploy files from $local_source"
	run mkdir -p "$install_dir/backup" "$install_dir/postgres" "$install_dir/monitoring"
	for f in $DEPLOY_FILES; do
		[[ -f $local_source/$f ]] || continue
		run cp -p "$local_source/$f" "$install_dir/$f"
	done
	note "docker-compose.build.yml builds from ../backend and ../frontend; use it from the checkout itself."
}

# --- .env --------------------------------------------------------------------

# write_env TEMPLATE OUT: the template with the required block filled in and
# the installer's choices appended. Secrets come from variables, never argv.
write_env() {
	local template=$1 out=$2 line
	{
		while IFS= read -r line || [[ -n $line ]]; do
			case $line in
			DOMAIN=) printf 'DOMAIN=%s\n' "$domain" ;;
			ADMIN_EMAIL=) printf 'ADMIN_EMAIL=%s\n' "$admin_email" ;;
			ADMIN_PASSWORD=)
				if [[ -n $admin_password ]]; then
					printf '%s\n' "$GENERATED_MARK"
				fi
				printf 'ADMIN_PASSWORD=%s\n' "$admin_password"
				;;
			DB_PASSWORD=) printf 'DB_PASSWORD=%s\n' "$db_password" ;;
			JWT_SECRET_KEY=) printf 'JWT_SECRET_KEY=%s\n' "$jwt_secret" ;;
			PLUGIN_SECRET_KEY=) printf 'PLUGIN_SECRET_KEY=%s\n' "$plugin_secret" ;;
			# Filled in even without the minio profile, so enabling it later
			# never starts MinIO with an empty (default) root password.
			"# MINIO_ROOT_PASSWORD=") printf 'MINIO_ROOT_PASSWORD=%s\n' "$minio_password" ;;
			PAYVERGE_VERSION=*) printf 'PAYVERGE_VERSION=%s\n' "$version" ;;
			*) printf '%s\n' "$line" ;;
			esac
		done <"$template"
		printf '\n# ==== Set by install.sh on %s ====\n' "$(date -u +%Y-%m-%d)"
		[[ -z $acme_email ]] || printf 'ACME_EMAIL=%s\n' "$acme_email"
		[[ -z ${COMPOSE_PROJECT_NAME:-} ]] || printf 'COMPOSE_PROJECT_NAME=%s\n' "$COMPOSE_PROJECT_NAME"
		[[ -z $http_port || $http_port == 80 ]] || printf 'HTTP_PORT=%s\n' "$http_port"
		[[ -z $https_port || $https_port == 443 ]] || printf 'HTTPS_PORT=%s\n' "$https_port"
		if [[ -n $https_port && ${https_port##*:} != 443 ]]; then
			printf 'PUBLIC_URL=https://%s:%s\n' "$domain" "${https_port##*:}"
		fi
		if is_true "$demo"; then
			printf 'DEMO_DATA=true\n'
			# Serve the core showroom venue's storefront at "/" (the same slug
			# the public-demo overlay uses) instead of the venue
			# directory. A slug that no longer exists (after `demo reset`)
			# falls back to the directory, so this is safe to leave.
			printf 'PRIMARY_VENUE=bodegon-mesa-larga\n'
		fi
		if [[ $(id -u) -ne 0 ]]; then
			printf 'BACKUP_UID=%s\nBACKUP_GID=%s\n' "$(id -u)" "$(id -g)"
		fi
	} >"$out"
}

# set_env_key FILE KEY VALUE: replace (or append) KEY=VALUE, keeping mode 600.
set_env_key() {
	local file=$1 key=$2 value=$3 tmp line replaced=0
	tmp=$(mktemp "$file.XXXXXX")
	chmod 600 "$tmp"
	while IFS= read -r line || [[ -n $line ]]; do
		if [[ $line == "$key="* ]]; then
			[[ $replaced == 1 ]] || printf '%s=%s\n' "$key" "$value"
			replaced=1
		elif [[ $line == "$GENERATED_MARK" && $key == ADMIN_PASSWORD && -z $value ]]; then
			continue
		else
			printf '%s\n' "$line"
		fi
	done <"$file" >"$tmp"
	[[ $replaced == 1 ]] || printf '%s=%s\n' "$key" "$value" >>"$tmp"
	mv "$tmp" "$file"
}

# --- checks before starting ----------------------------------------------------

port_in_use_by_others() { # port_in_use_by_others PORT
	local port=$1 ours
	if have ss; then
		ss -Hltn "sport = :$port" 2>/dev/null | grep -q . || return 1
	elif have lsof; then
		lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1 || return 1
	else
		return 1
	fi
	ours=$(docker ps -q --filter "label=com.docker.compose.project=$(project_name)" --filter "label=com.docker.compose.service=caddy" 2>/dev/null || true)
	[[ -z $ours ]]
}

# behind_proxy: .env has TLS_TERMINATION=proxy (another web server on this
# host terminates TLS and forwards plain HTTP to Caddy on HTTP_PORT).
behind_proxy() {
	[[ $(env_get TLS_TERMINATION "$env_file") == proxy ]]
}

# caddy_http_addr: where the web server in front reaches Caddy.
caddy_http_addr() {
	local p=${http_port:-80}
	[[ $p == *:* ]] || p=127.0.0.1:$p
	printf 'http://%s' "$p"
}

network_hints() {
	local p addrs=""
	# HTTP_PORT/HTTPS_PORT may carry a bind address (127.0.0.1:8080).
	for p in "${http_port:-80}" "${https_port:-443}"; do
		if port_in_use_by_others "${p##*:}"; then
			warn "port ${p##*:} is already in use on this host; stop that service, pass --http-port/--https-port, or put Payverge behind it (README.md, \"Behind another web server\")"
		fi
	done
	if behind_proxy; then
		note "TLS_TERMINATION=proxy: your web server serves https://$domain and forwards it to $(caddy_http_addr)"
		return 0
	fi
	if internal_tls_name "$domain"; then
		return 0
	fi
	# getent and host fail for a name that does not resolve yet; that is a
	# hint below, not an error (pipefail would otherwise end the script).
	if have getent; then
		addrs=$(getent ahosts "$domain" 2>/dev/null | awk '{print $1}' | sort -u | tr '\n' ' ') || addrs=""
	elif have host; then
		addrs=$(host "$domain" 2>/dev/null | awk '/has (IPv6 )?address/ {print $NF}' | sort -u | tr '\n' ' ') || addrs=""
	fi
	if [[ -n $addrs ]]; then
		note "$domain resolves to: $addrs"
		note "it must be this server's public address, with ports 80 and 443 open (e.g. ufw allow 80,443/tcp)."
	else
		warn "$domain does not resolve yet. Create its A/AAAA record; Caddy keeps retrying the certificate."
	fi
	if [[ ${http_port:-80} != 80 || ${https_port:-443} != 443 ]]; then
		warn "a public certificate needs ports 80 and 443 reachable from the internet (HTTP or TLS-ALPN challenge)."
	fi
}

# --- wait for the stack --------------------------------------------------------

# wait_ready: return 0 once the backend answers /api/v1/health/ready.
# Otherwise print its log, set ready_error and return 1.
wait_ready() {
	local deadline state restarts=0
	ready_error=""
	deadline=$((SECONDS + READY_TIMEOUT))
	printf '    waiting for the backend (the first start runs the database migrations)'
	while ((SECONDS < deadline)); do
		if compose exec -T caddy wget -q -O /dev/null -T 5 http://backend:8080/api/v1/health/ready >/dev/null 2>&1; then
			printf ' ready\n'
			return 0
		fi
		state=$(compose ps -a --format '{{.State}}' backend 2>/dev/null || true)
		case $state in
		restarting) restarts=$((restarts + 1)) ;;
		exited | dead) restarts=99 ;;
		esac
		if ((restarts >= 3)); then
			printf '\n'
			compose logs --tail 40 backend >&2 || true
			ready_error="the backend keeps stopping. The log above names the problem; fix $env_file and run: docker compose up -d"
			return 1
		fi
		printf '.'
		sleep 5
	done
	printf '\n'
	compose logs --tail 40 backend >&2 || true
	ready_error="the backend was not ready after ${READY_TIMEOUT}s. Check: docker compose logs backend"
	return 1
}

# start_stack: pull (or build) and `docker compose up -d`. When Compose
# fails, show the services and their recent logs before stopping.
start_stack() {
	local status=0
	if [[ $build == 1 ]]; then
		compose up -d --build --remove-orphans || status=$?
	else
		compose pull --quiet || warn "pulling the images failed; starting with what is already here"
		compose up -d --remove-orphans || status=$?
	fi
	if ((status == 0)) && [[ $reinstall == 1 ]]; then
		# The Caddy config files are bind-mounted one by one, and replacing
		# them gives them new inodes: a running caddy keeps serving the old
		# ones, and `up -d` does not recreate it when its compose definition
		# did not change. Recreate it so this run's Caddyfile is the one in use.
		compose up -d --force-recreate --no-deps caddy || {
			status=$?
			say "" >&2
			compose ps -a >&2 || true
			compose logs --tail 20 >&2 || true
			die "recreating caddy with the new Caddyfile failed (exit $status); the output above shows why. Fix the cause and run install.sh again."
		}
	fi
	((status != 0)) || return 0
	say "" >&2
	compose ps -a >&2 || true
	compose logs --tail 20 >&2 || true
	die "docker compose up -d failed (exit $status); the output above names the service. Fix the cause and run install.sh again."
}

# bootstrap_outcome: the newest line in which the backend said what it did
# with ADMIN_EMAIL/ADMIN_PASSWORD (backend/cmd/app, ensureEnvBootstrapAdmin):
# created, took over an account, ignored the password, or did nothing.
bootstrap_outcome() {
	compose logs --no-log-prefix backend 2>/dev/null |
		grep -E 'Bootstrap admin (NOT (created|applied)|for .* failed|skipped|.* created \(user id|.* took it over)|ADMIN_PASSWORD ignored' |
		tail -n 1 || true
}

# pre_upgrade_backup: new images run their migrations on the existing
# database, and migrations only go forward. Before anything changes, take a
# backup set with the files and version that are installed now, so the
# upgrade can be rolled back (README.md, "Upgrades").
pre_upgrade_backup() {
	local reason
	[[ -f $env_file && -f $install_dir/docker-compose.yml && -f $install_dir/backup/backup.sh ]] || return 0
	db_volume_exists || return 0
	if [[ $build == 1 || $(env_get COMPOSE_FILE "$env_file") == *docker-compose.build.yml* ]]; then
		reason="the images are rebuilt from source"
	elif [[ $version == latest ]]; then
		reason="PAYVERGE_VERSION=latest pulls the newest images"
	elif [[ $version != "${previous_version#v}" ]]; then
		reason="${previous_version:-an unknown version} -> $version"
	else
		return 0
	fi
	if [[ $no_backup == 1 ]]; then
		warn "upgrading without a backup set first (--no-backup)"
		return 0
	fi
	step "Taking a backup before the upgrade ($reason)"
	if [[ $dry_run == 1 ]]; then
		run docker compose run --rm -T backup once
		return 0
	fi
	# backup.sh logs "set complete: daily/<stamp> (...)"; keep that name. The
	# nightly job adds newer sets after the upgrade, which already carry the
	# new schema, so "the newest set" is the wrong one to roll back to.
	local log stamp backup_status=0
	log=$(mktemp "${TMPDIR:-/tmp}/payverge-backup.XXXXXX")
	compose run --rm -T backup once 2>&1 | tee "$log" || backup_status=${PIPESTATUS[0]}
	stamp=$(sed -n 's|.*set complete: daily/\([0-9]\{8\}T[0-9]\{6\}Z\).*|\1|p' "$log" | tail -n 1)
	rm -f "$log"
	((backup_status == 0)) ||
		die "the backup before the upgrade failed, so nothing was changed. Fix the cause shown above, or re-run with --no-backup to upgrade without one."
	if [[ -z $stamp ]]; then
		warn "could not read the name of the pre-upgrade backup set; to roll back, use the set in backups/daily taken just before this upgrade, not a later nightly one (README.md, \"Upgrades\")"
		return 0
	fi
	note "pre-upgrade backup set: daily/$stamp (version ${previous_version:-unknown})"
	note "to roll back to it (README.md, \"Upgrades\"):"
	say "    docker compose stop backend frontend"
	if [[ -n ${previous_version#v} ]]; then
		say "    set PAYVERGE_VERSION=${previous_version#v} in .env"
	fi
	say "    docker compose --profile restore run --rm restore daily/$stamp --yes"
	say "    docker compose up -d"
}

# warn_probe WHAT: the public check named WHAT failed. The hints are the ones
# probe_https used to print itself; main calls this after the summary.
warn_probe() {
	if [[ $probe_scheme == http ]]; then
		warn "$1 does not answer on http://$probe_bind:$probe_port yet. Check: docker compose logs caddy"
	else
		warn "$1 does not answer on port $probe_port yet. For a public domain check DNS and ports 80/443, then: docker compose logs caddy"
	fi
}

probe_https() {
	local port=${https_port:-443} scheme=https bind=127.0.0.1 backend frontend resolve=() i
	local backend_ok=0 frontend_ok=0
	have curl || return 0
	if behind_proxy; then
		# Caddy serves plain HTTP; your web server does the HTTPS part.
		port=${http_port:-80} scheme=http
	fi
	# A bind address on the port (127.0.0.1:8443) is where Caddy listens.
	[[ $port != *:* || ${port%:*} == 0.0.0.0 ]] || bind=${port%:*}
	port=${port##*:}
	backend="$scheme://$domain:$port/api/v1/health/live"
	frontend="$scheme://$domain:$port/"
	[[ $domain =~ ^[0-9.]+$ ]] || resolve=(--resolve "$domain:$port:$bind")
	for ((i = 1; i <= PROBE_ATTEMPTS; i++)); do
		if [[ $backend_ok != 1 ]] && curl -fsS -k -o /dev/null --max-time 5 ${resolve[@]+"${resolve[@]}"} "$backend" 2>/dev/null; then
			backend_ok=1
		fi
		if [[ $frontend_ok != 1 ]] && curl -fsS -k -o /dev/null --max-time 5 ${resolve[@]+"${resolve[@]}"} "$frontend" 2>/dev/null; then
			frontend_ok=1
		fi
		if [[ $backend_ok == 1 && $frontend_ok == 1 ]]; then
			if [[ $scheme == http ]]; then
				note "Caddy answers on http://$bind:$port; point your web server for $domain there"
			else
				note "HTTPS answers on port $port"
			fi
			return 0
		fi
		((i == PROBE_ATTEMPTS)) || sleep 5
	done
	# Remember the miss. main() warns and exits only after the summary, so a
	# generated admin password is still shown once.
	probe_failed=1
	probe_scheme=$scheme
	probe_bind=$bind
	probe_port=$port
	[[ $backend_ok == 1 ]] || probe_backend_failed=1
	[[ $frontend_ok == 1 ]] || probe_frontend_failed=1
}

# --- main ----------------------------------------------------------------------

# Everything runs from main, so a truncated download cannot run half a script.
main() {
	normalize_version
	[[ -z $http_port ]] || valid_port_spec "$http_port" || die "--http-port must be a port (1-65535) or ADDR:PORT, e.g. 8080 or 127.0.0.1:8080"
	[[ -z $https_port ]] || valid_port_spec "$https_port" || die "--https-port must be a port (1-65535) or ADDR:PORT, e.g. 8443 or 127.0.0.1:8443"
	[[ -z ${COMPOSE_PROJECT_NAME:-} ]] || valid_project_name "$COMPOSE_PROJECT_NAME" ||
		die "COMPOSE_PROJECT_NAME must be lowercase letters, digits, '-' or '_', starting with a letter or digit"
	[[ -z $acme_email ]] || valid_email "$acme_email" || die "--acme-email is not an email address"
	[[ -z $admin_email ]] || valid_email "$admin_email" || die "'$admin_email' is not an email address"
	[[ -z $domain ]] || normalize_domain

	say "${bold}Payverge installer${reset}"
	[[ $dry_run != 1 ]] || say "${dim}dry run: nothing is downloaded, written or started${reset}"

	check_docker

	# Where to install.
	if [[ -z $install_dir ]]; then
		if [[ -n $local_source ]]; then
			install_dir=$local_source
		elif [[ -n $installed_dir ]]; then
			install_dir=$installed_dir
		elif [[ $(id -u) -eq 0 ]]; then
			install_dir=/opt/payverge
		else
			install_dir=$HOME/payverge
		fi
	fi
	case $install_dir in
	/*) ;;
	*) install_dir=$PWD/$install_dir ;;
	esac
	[[ $install_dir == / ]] || install_dir=${install_dir%/}
	env_file=$install_dir/.env
	step "Install directory: $install_dir"

	in_place=0
	[[ -n $local_source && $install_dir == "$local_source" ]] && in_place=1
	if [[ $build == 1 && $in_place != 1 ]]; then
		die "--build works from a clone of the repository, in place: ./deploy/install.sh --build (without --dir)"
	fi

	# Re-running without --version keeps the version pinned in .env.
	previous_version=$(env_get PAYVERGE_VERSION "$env_file")
	# An existing .env means an earlier run started the stack (see start_stack).
	reinstall=0
	[[ -f $env_file ]] && reinstall=1
	if [[ $version_requested != 1 && -n ${previous_version#v} ]]; then
		version=${previous_version#v}
	fi

	# Whether images are built from this checkout: --build, or an existing
	# .env whose COMPOSE_FILE already lists docker-compose.build.yml (the
	# same check repeated after .env is written, known here so the version
	# pin below can tell a source install from a release install).
	from_source=$build
	[[ $(env_get COMPOSE_FILE "$env_file") != *docker-compose.build.yml* ]] || from_source=1

	# Pin a real version. Images built here are payverge-*:local, so a source
	# install records "local". Otherwise "latest" (a moving tag) and a
	# leftover "local" resolve to the newest release, for a clone, a copy and
	# a release install alike.
	if [[ $from_source == 1 ]]; then
		version=local
	elif [[ $version == latest || $version == local ]]; then
		if [[ $dry_run == 1 ]]; then
			run curl -fsSLI "$RELEASES_URL/latest" "(find the newest release)"
			version=X.Y.Z
		else
			version=$(resolve_latest)
		fi
	fi

	# Before an upgrade changes anything: a backup of the current data.
	pre_upgrade_backup

	# Fetch or copy the deploy files.
	if [[ $in_place == 1 ]]; then
		note "using the checkout in place"
	elif [[ -n $local_source ]]; then
		copy_checkout
	else
		fetch_release "$version"
	fi

	# Settings: reuse .env, or collect what a new one needs.
	admin_password=""
	if [[ -f $env_file && $force != 1 ]]; then
		step "Keeping the existing .env (pass --force to rewrite it)"
		for flag_value in "$domain" "$admin_email" "$acme_email" "$demo" "$http_port" "$https_port"; do
			if [[ -n $flag_value ]]; then
				warn "settings flags are ignored while .env exists; edit $env_file instead"
				break
			fi
		done
		if [[ $version != "$(env_get PAYVERGE_VERSION "$env_file")" ]]; then
			step "Setting PAYVERGE_VERSION=$version"
			[[ $dry_run == 1 ]] || set_env_key "$env_file" PAYVERGE_VERSION "$version"
		fi
		if [[ $(id -u) -ne 0 ]] && ! env_has BACKUP_UID "$env_file"; then
			step "Setting BACKUP_UID=$(id -u) and BACKUP_GID=$(id -g) (backup sets readable without root)"
			if [[ $dry_run != 1 ]]; then
				set_env_key "$env_file" BACKUP_UID "$(id -u)"
				set_env_key "$env_file" BACKUP_GID "$(id -g)"
			fi
		fi
		domain=$(env_get DOMAIN "$env_file")
		admin_email=$(env_get ADMIN_EMAIL "$env_file")
		http_port=$(env_get HTTP_PORT "$env_file")
		https_port=$(env_get HTTPS_PORT "$env_file")
		[[ -n $domain ]] || die "$env_file has no DOMAIN; fill it in, or re-run with --force"
	else
		if [[ -z $domain ]] && interactive; then
			ask domain "Domain name (its DNS pointing at this server), or localhost for a trial" "localhost"
		fi
		[[ -n $domain ]] || die "no domain: pass --domain NAME (or --domain localhost for a trial)"
		normalize_domain
		if loopback_name "$domain"; then
			bind_loopback
			note "local trial: Caddy listens on $http_port and $https_port only (pass --https-port 0.0.0.0:443 to open it to the network)"
		fi

		if [[ -z $admin_email ]] && interactive; then
			ask admin_email "Admin email (your sign-in)"
		fi
		[[ -n $admin_email ]] || die "no admin email: pass --admin-email EMAIL"
		valid_email "$admin_email" || die "'$admin_email' is not an email address"

		if [[ -z $demo ]] && interactive; then
			ask demo "Load demo restaurants to explore? (y/N)" "n"
		fi
		if is_true "$demo"; then demo=1; else demo=0; fi

		template=$install_dir/.env.example
		if [[ ! -f $template && $dry_run != 1 ]]; then
			die "missing $template"
		fi

		db_password="" jwt_secret="" plugin_secret="" minio_password=""
		if [[ -f $env_file ]]; then
			# --force: keep what the data on disk depends on.
			db_password=$(env_get DB_PASSWORD "$env_file")
			jwt_secret=$(env_get JWT_SECRET_KEY "$env_file")
			plugin_secret=$(env_get PLUGIN_SECRET_KEY "$env_file")
			minio_password=$(env_get MINIO_ROOT_PASSWORD "$env_file")
			backup_env="$env_file.bak-$(date -u +%Y%m%dT%H%M%SZ)"
			step "Rewriting .env (--force); the old one is kept as $(basename "$backup_env")"
			note "DB_PASSWORD, JWT_SECRET_KEY, PLUGIN_SECRET_KEY and MINIO_ROOT_PASSWORD are carried over; copy any other custom settings back by hand"
			run cp -p "$env_file" "$backup_env"
		elif db_volume_exists; then
			die "a database volume from an earlier install exists, but $env_file (with its password) does not. Put that .env back, or delete the old data with: docker compose -p $(project_name) down -v"
		fi
		[[ -n $db_password ]] || db_password=$(rand_hex 24)
		[[ -n $jwt_secret ]] || jwt_secret=$(rand_b64 48)
		[[ -n $plugin_secret ]] || plugin_secret=$(rand_hex 32)
		[[ -n $minio_password ]] || minio_password=$(rand_hex 24)
		if db_volume_exists; then
			note "existing database: its admin account is kept (README.md, \"Admin access\", resets a password)"
		else
			admin_password=$(gen_admin_password)
		fi

		step "Writing $env_file (mode 600)"
		if [[ $dry_run == 1 ]]; then
			note "DOMAIN=$domain"
			note "ADMIN_EMAIL=$admin_email"
			note "ADMIN_PASSWORD, DB_PASSWORD, JWT_SECRET_KEY, PLUGIN_SECRET_KEY, MINIO_ROOT_PASSWORD: <generated, not shown>"
			note "PAYVERGE_VERSION=$version, COMPOSE_PROFILES=backup$([[ $demo == 1 ]] && printf ', DEMO_DATA=true')"
			[[ -z ${COMPOSE_PROJECT_NAME:-} ]] || note "COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME"
			[[ -z $http_port || $http_port == 80 ]] || note "HTTP_PORT=$http_port"
			[[ -z $https_port || $https_port == 443 ]] || note "HTTPS_PORT=$https_port"
		else
			mkdir -p "$install_dir"
			(
				umask 077
				tmp_env=$(mktemp "$env_file.XXXXXX")
				write_env "$template" "$tmp_env"
				chmod 600 "$tmp_env"
				mv "$tmp_env" "$env_file"
			)
		fi
	fi

	# --build: images come from this checkout (docker-compose.build.yml).
	if [[ $build == 1 ]]; then
		compose_files="docker-compose.yml:docker-compose.build.yml"
		if [[ $(env_get COMPOSE_FILE "$env_file") != "$compose_files" ]]; then
			step "Setting COMPOSE_FILE=$compose_files (images build from source)"
			[[ $dry_run == 1 ]] || set_env_key "$env_file" COMPOSE_FILE "$compose_files"
		fi
	fi
	[[ $(env_get COMPOSE_FILE "$env_file") != *docker-compose.build.yml* ]] || build=1

	if [[ ! -d $install_dir/backups ]]; then
		run mkdir -p "$install_dir/backups"
		run chmod 700 "$install_dir/backups"
	fi

	proxy_cidrs=$(env_get TRUSTED_PROXY_CIDRS "$env_file")
	if [[ -n $proxy_cidrs ]] && ! valid_proxy_cidrs "$proxy_cidrs"; then
		die "TRUSTED_PROXY_CIDRS in $env_file must be space-separated IPv4/IPv6 addresses or CIDRs (no commas, nothing broader than /8 for IPv4 or /16 for IPv6; use private_ranges to trust every private range, including fc00::/7), e.g. TRUSTED_PROXY_CIDRS=\"10.0.0.0/24 fd00::/64\""
	fi

	# TLS_TERMINATION=proxy: Caddy serves plain HTTP for the web server in
	# front. Published on every interface (the compose default), that HTTP
	# port would let clients go around the proxy and its TLS, so both ports
	# need a bind address. 0.0.0.0:PORT is an explicit opt-in.
	if behind_proxy; then
		local_http=$(env_get HTTP_PORT "$env_file")
		local_https=$(env_get HTTPS_PORT "$env_file")
		if [[ ${local_http:-80} != *:* || ${local_https:-443} != *:* ]]; then
			die "TLS_TERMINATION=proxy needs HTTP_PORT and HTTPS_PORT with a bind address in $env_file, e.g. HTTP_PORT=127.0.0.1:8080 and HTTPS_PORT=127.0.0.1:8443. Without one, Caddy's plain-HTTP port is published on every interface and clients can bypass your web server (README.md, \"Behind another web server\")."
		fi
		http_port=$local_http
		https_port=$local_https
	fi

	step "Network"
	network_hints

	if [[ $start != 1 ]]; then
		step "Not starting (--no-start)"
		say "  Start it later with: cd $install_dir && ./install.sh"
		if grep -qxF "$GENERATED_MARK" "$env_file" 2>/dev/null; then
			say "  That shows the generated admin password once and takes it back out of .env."
			say "  (A plain 'docker compose up -d' works too, but the password then stays in .env as ADMIN_PASSWORD.)"
		fi
		exit 0
	fi

	if [[ $build == 1 ]]; then
		step "Building and starting Payverge (the first build takes 10-30 minutes and about 8 GB of RAM)"
	else
		step "Starting Payverge (the first start downloads about 1 GB of images)"
	fi
	if [[ $dry_run == 1 ]]; then
		if [[ $build == 1 ]]; then
			run docker compose up -d --build --remove-orphans
		else
			run docker compose pull
			run docker compose up -d --remove-orphans
		fi
		[[ $reinstall == 0 ]] || run docker compose up -d --force-recreate --no-deps caddy "(load the new Caddyfile)"
		run wait for http://backend:8080/api/v1/health/ready "(up to ${READY_TIMEOUT}s)"
		say ""
		say "Dry run complete. Run again without --dry-run to install."
		exit 0
	fi
	start_stack
	wait_ready || die "$ready_error"

	# Take a generated ADMIN_PASSWORD back out of .env (and out of the
	# container) once the backend has used it. The value is shown only when
	# the backend says it set it; when it says nothing or refused, the
	# password stays in .env so the next start retries.
	shown_password=""
	password_note="unchanged"
	if grep -qxF "$GENERATED_MARK" "$env_file" && [[ -n $(env_get ADMIN_PASSWORD "$env_file") ]]; then
		outcome=$(bootstrap_outcome)
		remove_password=0
		case $outcome in
		*"Bootstrap admin NOT "* | *"Bootstrap admin for "*" failed"* | *"Bootstrap admin skipped"*)
			warn "the backend did not set up the admin account; the password stays in .env (ADMIN_PASSWORD) so the next start retries:"
			printf '    %s\n' "$outcome" >&2
			password_note="not set (see the warning above)"
			;;
		*" created (user id"*)
			shown_password=$(env_get ADMIN_PASSWORD "$env_file")
			remove_password=1
			;;
		*" took it over"*)
			shown_password=$(env_get ADMIN_PASSWORD "$env_file")
			remove_password=1
			warn "$admin_email already had a (non-admin) account. It is now the admin with the password below; its old password and other sign-in methods no longer work, and its sessions were signed out."
			;;
		*"ADMIN_PASSWORD ignored"*)
			warn "$admin_email already had an account; its password was NOT changed. Reset it as shown in README.md (\"Admin access\")."
			remove_password=1
			;;
		*)
			warn "the backend log does not say whether it created the admin account; the password stays in .env (ADMIN_PASSWORD). Check: docker compose logs backend | grep -i admin"
			password_note="not confirmed; it is ADMIN_PASSWORD in $env_file"
			;;
		esac
		if [[ $remove_password == 1 ]]; then
			set_env_key "$env_file" ADMIN_PASSWORD ""
			# The password is printed below even if this restart fails.
			if ! compose up -d backend >/dev/null 2>&1 || ! wait_ready; then
				warn "the backend did not come back after ADMIN_PASSWORD was removed from .env${ready_error:+: $ready_error}. Run: docker compose up -d"
			fi
		fi
	fi

	probe_https

	public_url=$(env_get PUBLIC_URL "$env_file")
	[[ -n $public_url ]] || public_url="https://$domain"

	say ""
	say "${green}${bold}Payverge is running.${reset}"
	say ""
	say "  URL          $public_url"
	say "  Admin email  $admin_email"
	if [[ -n $shown_password ]]; then
		say "  Password     ${bold}$shown_password${reset}"
		say ""
		say "  Save this password in your password manager now. It is shown only"
		say "  once and is not stored on this server."
	else
		say "  Password     $password_note"
	fi
	say ""
	say "Next steps:"
	if internal_tls_name "$domain"; then
		say "  - Browsers warn about the certificate: Caddy issued it from its own local CA. To trust it:"
		say "      cd $install_dir && docker compose cp caddy:/data/caddy/pki/authorities/local/root.crt ./payverge-local-ca.crt"
		say "    and import payverge-local-ca.crt into your system or browser trust store."
	fi
	if behind_proxy; then
		say "  - Your web server must forward https://$domain to $(caddy_http_addr) (README.md, \"Behind another web server\")."
	fi
	say "  - Lost password, upgrades, backups and restore: $install_dir/README.md"
	say "  - Backups run nightly into $install_dir/backups; copy them off this server."
	say "  - Settings live in $install_dir/.env; apply a change with: docker compose up -d"

	if [[ $probe_failed == 1 ]]; then
		if [[ $probe_backend_failed == 1 ]]; then
			warn_probe "backend /api/v1/health/live"
		fi
		if [[ $probe_frontend_failed == 1 ]]; then
			warn_probe "frontend /"
		fi
		exit 1
	fi
}

main
