import fs from "node:fs";
import path from "node:path";

import {
  readRegistry,
  repoRootFromFrontend,
  type LocaleRegistry,
  type LocaleRegistryEntry,
} from "./common";

const generatedComment =
  "// Code generated by frontend/scripts/i18n/generate.ts; DO NOT EDIT.";

type GoScalarRegistryField = Exclude<
  keyof LocaleRegistryEntry,
  "requiredSurfaces"
>;

const goScalarFields: Array<[GoScalarRegistryField, string]> = [
  ["canonical", "Canonical"],
  ["pathSegment", "PathSegment"],
  ["sourceFolder", "SourceFolder"],
  ["displayName", "DisplayName"],
  ["nativeName", "NativeName"],
  ["direction", "Direction"],
  ["emailFamily", "EmailFamily"],
  ["promptFamily", "PromptFamily"],
  ["translationProviderTarget", "TranslationProviderTarget"],
  ["publicRoutes", "PublicRoutes"],
  ["operatorLocale", "OperatorLocale"],
  ["guestLocale", "GuestLocale"],
  ["publishable", "Publishable"],
];

const requiredSurfacesGoField = "RequiredSurfaces";

export interface GeneratedFilePaths {
  frontendGeneratedPath: string;
  backendGeneratedPath: string;
}

export function generatedFilePaths(repoRoot: string): GeneratedFilePaths {
  return {
    frontendGeneratedPath: path.join(
      repoRoot,
      "frontend",
      "src",
      "i18n",
      "generated",
      "locales.ts",
    ),
    backendGeneratedPath: path.join(
      repoRoot,
      "backend",
      "internal",
      "locales",
      "registry_generated.go",
    ),
  };
}

interface RunGenerateOptions {
  repoRoot: string;
  check: boolean;
}

// runGenerate is the testable core. In write mode it (re)writes both generated
// files and returns 0. In --check mode it generates both outputs IN MEMORY,
// compares them against what is on disk, and returns 1 (without writing
// anything) if either differs — so CI / the pre-commit hook can fail a
// registry.json edit that was never followed by `npm run i18n:generate`.
export function runGenerate(opts: RunGenerateOptions): number {
  const registry = readRegistry(opts.repoRoot);
  const { frontendGeneratedPath, backendGeneratedPath } = generatedFilePaths(
    opts.repoRoot,
  );

  const targets: Array<{ filePath: string; expected: string }> = [
    { filePath: frontendGeneratedPath, expected: generateTypeScript(registry) },
    { filePath: backendGeneratedPath, expected: generateGo(registry) },
  ];

  if (opts.check) {
    const stale = targets.filter(
      ({ filePath, expected }) => readFileOrNull(filePath) !== expected,
    );

    if (stale.length === 0) {
      console.log("i18n generated files are in sync with locales/registry.json");
      return 0;
    }

    for (const { filePath } of stale) {
      console.error(
        `i18n drift: ${path.relative(
          opts.repoRoot,
          filePath,
        )} is out of sync with locales/registry.json.`,
      );
    }
    console.error(
      "Run `npm run i18n:generate` (from frontend/) and commit the regenerated files.",
    );
    return 1;
  }

  for (const { filePath, expected } of targets) {
    writeGeneratedFile(filePath, expected);
    console.log(`Generated ${path.relative(opts.repoRoot, filePath)}`);
  }

  return 0;
}

function main(): void {
  const check = process.argv.slice(2).includes("--check");
  const exitCode = runGenerate({ repoRoot: repoRootFromFrontend(), check });

  process.exitCode = exitCode;
}

function readFileOrNull(filePath: string): string | null {
  try {
    return fs.readFileSync(filePath, "utf8");
  } catch {
    return null;
  }
}

function writeGeneratedFile(filePath: string, contents: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, contents);
}

export function generateTypeScript(registry: LocaleRegistry): string {
  const locales = sortedLocales(registry);

  return `${generatedComment}

export const defaultLocale = ${JSON.stringify(registry.defaultLocale)} as const;

export const localeRegistry = ${JSON.stringify(locales, null, 2)} as const;

export type LocaleCode = keyof typeof localeRegistry;
`;
}

export function generateGo(registry: LocaleRegistry): string {
  const entries = Object.entries(sortedLocales(registry))
    .map(([canonical, locale]) => generateGoLocale(canonical, locale))
    .join("\n");

  return `${generatedComment}

package locales

const defaultLocale = ${goString(registry.defaultLocale)}

var generatedRegistry = map[string]Locale{
${entries}
}
`;
}

function generateGoLocale(
  canonical: string,
  locale: LocaleRegistryEntry,
): string {
  const maxGoFieldLength = Math.max(
    requiredSurfacesGoField.length,
    ...goScalarFields.map(([, goField]) => goField.length),
  );
  const scalarFields = goScalarFields
    .map(([sourceField, goField]) => {
      const value = locale[sourceField];
      const goValue =
        typeof value === "boolean" ? String(value) : goString(value);
      const padding = " ".repeat(maxGoFieldLength - goField.length + 1);

      return `\t\t${goField}:${padding}${goValue},`;
    })
    .join("\n");
  const requiredSurfacesPadding = " ".repeat(
    maxGoFieldLength - requiredSurfacesGoField.length + 1,
  );
  const fields = [
    scalarFields,
    `\t\t${requiredSurfacesGoField}:${requiredSurfacesPadding}${goStringSlice(
      locale.requiredSurfaces,
    )},`,
  ].join("\n");

  return `\t${goString(canonical)}: {
${fields}
\t},`;
}

function sortedLocales(
  registry: LocaleRegistry,
): Record<string, LocaleRegistryEntry> {
  return Object.keys(registry.locales)
    .sort(compareStrings)
    .reduce<Record<string, LocaleRegistryEntry>>((locales, canonical) => {
      locales[canonical] = registry.locales[canonical];
      return locales;
    }, {});
}

function compareStrings(left: string, right: string): number {
  if (left < right) {
    return -1;
  }

  if (left > right) {
    return 1;
  }

  return 0;
}

function goString(value: string): string {
  return JSON.stringify(value);
}

function goStringSlice(values: string[]): string {
  return `[]string{${values.map(goString).join(", ")}}`;
}

if (
  process.argv[1] &&
  /^generate\.[jt]s$/.test(path.basename(process.argv[1]))
) {
  main();
}
