#!/usr/bin/env bash
# Regenerates docs/licensing/THIRD_PARTY_LICENSES.md from:
#   - go-licenses report over the backend image binaries (default build),
#     with go-overrides.tsv applied where the detection still matches
#   - the frontend production npm tree (npm-licenses.mjs report)
#   - the OFL.txt files next to the bundled fonts
#
# Usage: scripts/licenses/generate-third-party.sh [--check]
#   --check  regenerate into a temp file and fail if the committed copy differs
# Needs the same tooling as check.sh. The output is deterministic (sorted, no
# timestamps), so a re-run with unchanged inputs produces no diff.
set -euo pipefail

# shellcheck source=scripts/licenses/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

OUT="$LIC_ROOT/docs/licensing/THIRD_PARTY_LICENSES.md"
mode="write"
case "${1:-}" in
  "") ;;
  --check) mode=check ;;
  -h | --help)
    sed -n '2,11p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 0
    ;;
  *) lic_die "unknown argument $1" ;;
esac

work="$(mktemp -d "${TMPDIR:-/tmp}/payverge-third-party.XXXXXX")"
trap 'rm -rf "$work"' EXIT

go_section() {
  (
    lic_setup_go
    local golic tpl
    golic="$(lic_go_licenses_bin)"
    tpl="$work/report.tpl"
    printf '%s\n' '{{range .}}{{.Name}}	{{.Version}}	{{.LicenseName}}	{{.LicenseURL}}' '{{end}}' >"$tpl"
    "$golic" report --template "$tpl" --ignore "$LIC_GO_MODULE/" "${LIC_GO_TARGETS[@]}" \
      >"$work/go.tsv" 2>"$work/go.err" ||
      { cat "$work/go.err" >&2; lic_die "go-licenses report failed"; }
    printf '%s\n' "$GOOS" >"$work/goos"
  )
  lic_go_overrides >"$work/overrides.tsv"

  printf '## Go modules (backend image)\n\n'
  printf 'Packages linked into `./cmd/app`, `./cmd/email-smoke` and `./cmd/healthcheck`, the\n'
  printf 'binaries in the backend image, in the default build: no `whatsapp` tag,\n'
  printf '`GOOS=%s`, `CGO_ENABLED=0`. Detected with go-licenses %s. Rows marked `*` use\n' "$(cat "$work/goos")" "$GO_LICENSES_VERSION"
  printf 'an override from `scripts/licenses/go-overrides.tsv` (reasons below).\n\n'
  printf '| Package | Version | License | License text |\n| --- | --- | --- | --- |\n'
  awk -F'\t' -v OFS='\t' '
    NR == FNR { mod[NR] = $1; det[NR] = $2; lic[NR] = $3; n = NR; next }
    NF >= 3 {
      name = $1; ver = $2; l = $3; url = $4; mark = ""
      for (i = 1; i <= n; i++) {
        if ((name == mod[i] || index(name, mod[i] "/") == 1) && l == det[i]) {
          l = lic[i]; mark = " *"
          url = "https://pkg.go.dev/" name "@" ver "?tab=licenses"
        }
      }
      if (url == "" || url == "Unknown") url = "https://pkg.go.dev/" name "@" ver "?tab=licenses"
      # go-licenses resolves the LICENSE.txt of this nested module to a different
      # directory on macOS and on the Linux CI runner; link the stable page.
      if (name == "github.com/aws/aws-sdk-go-v2/internal/endpoints/v2") url = "https://pkg.go.dev/" name "@" ver "?tab=licenses"
      printf "| %s | %s | %s%s | [link](%s) |\n", name, ver, l, mark, url
    }' "$work/overrides.tsv" "$work/go.tsv" | LC_ALL=C sort

  printf '\n### Go overrides\n\n| Module | go-licenses detects | Distributed under | Why |\n| --- | --- | --- | --- |\n'
  awk -F'\t' '!/^[[:space:]]*(#|$)/ { printf "| %s | %s | %s | %s |\n", $1, $2, $3, $4 }' "$LIC_GO_OVERRIDES"
  printf '\n'
}

npm_section() {
  printf '## Frontend npm packages (production dependencies)\n\n'
  printf 'Every non-dev entry in `frontend/package-lock.json`, including optional\n'
  printf 'platform binaries such as the per-OS sharp/libvips and @napi-rs/canvas builds.\n'
  printf 'A deployment installs only the ones for its own platform. Licences come from\n'
  printf 'the lockfile, then the installed `package.json`, then\n'
  printf '`scripts/licenses/npm-overrides.tsv`.\n\n'
  node "$LIC_DIR/npm-licenses.mjs" report || lic_die "npm report failed"
  printf '\n'
}

font_section() {
  printf '## Fonts\n\n'
  printf 'Bundled under the SIL Open Font License 1.1. The full licence text sits next to\n'
  printf 'each family. The fonts are not relicensed under Apache-2.0.\n\n'
  printf '| Directory | License | Copyright |\n| --- | --- | --- |\n'
  local ofl first
  while IFS= read -r ofl; do
    first="$(head -n 1 "$LIC_ROOT/$ofl" | tr -d '\r')"
    printf '| `%s` | OFL-1.1 | %s |\n' "$(dirname "$ofl")" "${first//|/\\|}"
  done < <(git -C "$LIC_ROOT" ls-files -- 'frontend/public/fonts/**/OFL.txt' | LC_ALL=C sort)
  printf '\n'
}

{
  printf '# Third-party licences\n\n'
  printf '<!-- Generated by scripts/licenses/generate-third-party.sh. Do not edit by hand. -->\n\n'
  printf 'Payverge is licensed under Apache-2.0 (see `LICENSE`); required attributions\n'
  printf 'are in `NOTICE`. This file lists the third-party components a build of\n'
  printf 'Payverge ships. Regenerate it with `scripts/licenses/generate-third-party.sh`\n'
  printf 'after changing `backend/go.mod`, `frontend/package-lock.json`, the bundled\n'
  printf 'fonts or the override tables. `scripts/licenses/check.sh` enforces the\n'
  printf 'licence policy; `--check` on the generator fails when this file is stale.\n\n'
  go_section
  npm_section
  font_section
  printf '## Not covered here\n\n'
  printf -- '- **Container base images.** The frontend runs on `node:26-alpine`, the backend on\n'
  printf '  `gcr.io/distroless/static-debian12`. Their OS packages carry their own licences;\n'
  printf '  see each image'"'"'s documentation.\n'
  printf -- '- **`-tags whatsapp` builds.** The opt-in WhatsApp channel links `go.mau.fi/whatsmeow`\n'
  printf '  (MPL-2.0) and `go.mau.fi/libsignal` (GPL-3.0). A binary built with that tag is\n'
  printf '  GPL-3.0 as a whole. The project does not distribute such builds.\n'
  printf -- '- **Development dependencies** (build, lint and test tooling) are not shipped.\n'
  printf -- '- **Images and other media** are listed in `docs/licensing/CREDITS.md`.\n'
} >"$work/out.md"

if [[ $mode == check ]]; then
  if ! diff -u "$OUT" "$work/out.md" >"$work/diff"; then
    head -n 60 "$work/diff" >&2
    lic_die "docs/licensing/THIRD_PARTY_LICENSES.md is stale; run scripts/licenses/generate-third-party.sh"
  fi
  lic_log "THIRD_PARTY_LICENSES.md is up to date"
else
  mkdir -p "$(dirname "$OUT")"
  cp "$work/out.md" "$OUT"
  lic_log "wrote ${OUT#"$LIC_ROOT"/}"
fi
